--部门内调拨
SELECT * FROM GAMS_ASSETEXCHANMA_H gah WHERE gah.BIZ_JY00_ZHIDRY  NOT IN (SELECT RECID FROM GAMS_JC_PERSONNEL);
--校内资产处置
SELECT * FROM BIZ_JY00_INNERDISPREG_H bjih WHERE bjih.CREATEUSERID NOT IN (SELECT RECID FROM GAMS_JC_PERSONNEL);
SELECT * FROM BIZ_JY00_INNERDISPREG_H bjih WHERE bjih.BIZ_JY00_ZHIDBM NOT IN (SELECT RECID FROM GAMS_JC_DEPARTMENT gjd );
SELECT * FROM BIZ_JY00_INNERDISPREG_I bjih WHERE bjih.SHIYBMID NOT IN (SELECT RECID FROM GAMS_JC_DEPARTMENT gjd );
--建账
SELECT * FROM BIZ_JY00_GAMS_ASSETACCEPT_H bjgah WHERE BJGAH.BIZ_JY00_ZHIDBM NOT IN (SELECT RECID FROM GAMS_JC_DEPARTMENT gjd );



