CREATE TABLE GAMS_CARD_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD;
CREATE TABLE GAMS_CARD_CL_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_CL gcc ;
CREATE TABLE GAMS_CARD_FW_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_FW gcf ;
CREATE TABLE GAMS_CARD_GZW_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_GZW gcg ;
CREATE TABLE GAMS_CARD_JJYJZJ_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_JJYJZJ gcj ;
CREATE TABLE GAMS_CARD_TD_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_TD gct ;
CREATE TABLE GAMS_CARD_TSDA_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_TSDA gct ;
CREATE TABLE GAMS_CARD_TYSB_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_TYSB gct ;
CREATE TABLE GAMS_CARD_TZDZW_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_TZDZW gct ;
CREATE TABLE GAMS_CARD_WWHCLP_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_WWHCLP gcw ;
CREATE TABLE GAMS_CARD_WXZC_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_WXZC gcw ;
CREATE TABLE GAMS_CARD_ZYSB_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_ZYSB gcz ;

DELETE FROM GAMS_CARD;
DELETE FROM GAMS_CARD_CL;
DELETE FROM GAMS_CARD_FW;
DELETE FROM GAMS_CARD_GZW;
DELETE FROM GAMS_CARD_JJYJZJ;
DELETE FROM GAMS_CARD_TD;
DELETE FROM GAMS_CARD_TSDA;

DELETE FROM GAMS_CARD_TYSB;
DELETE FROM GAMS_CARD_TZDZW;
DELETE FROM GAMS_CARD_WWHCLP;
DELETE FROM GAMS_CARD_ZYSB;
DELETE FROM GAMS_CARD_WXZC;
DELETE FROM GAMS_CARD_TD;
DELETE FROM GAMS_CARD_TSDA;


SELECT * FROM GAMS_JC_ASSETSORT_GB gjag ;

SELECT * FROM GAMS_JC_ASSETCLASS gjag ;

DELETE FROM GAMS_JC_ASSETSORT_GB;
DELETE FROM GAMS_JC_ASSETCLASS;
DELETE FROM GAMS_JC_ASSETCLASS_GB;
DELETE FROM GAMS_JC_ASSETCLASS_IND;

SELECT * FROM NP_USER nu ;








