
--备份卡片
 CREATE TABLE GAMS_CARD_TYSB_bal1917 AS
SELECT
	*
FROM
	GAMS_CARD_TYSB;

CREATE TABLE GAMS_CARD_ZYSB_bal1917 AS
SELECT
	*
FROM
	GAMS_CARD_ZYSB;

CREATE TABLE GAMS_CARD_CL_bal1917 AS
SELECT
	*
FROM
	GAMS_CARD_CL;

CREATE TABLE GAMS_CARD_FW_bal1917 AS
SELECT
	*
FROM
	GAMS_CARD_FW;

CREATE TABLE GAMS_CARD_JJYJZJ_bal1917 AS
SELECT
	*
FROM
	GAMS_CARD_JJYJZJ;
--更新通用卡片已提折旧月数
 UPDATE
	GAMS_CARD_TYSB a
SET
	a.YITZJYS = a.YITZJYS -1
WHERE
	a.YITZJYS IS NOT NULL
	AND a.id IN (
	SELECT
		gab.CARD_ID
	FROM
		GAMS_ASSETDEPRECDETAIL_BAK0916 gab
	WHERE
		gab.JIZQJ = '202008');
--更新专用卡片已提折旧月数
 UPDATE
	GAMS_CARD_ZYSB a
SET
	a.YITZJYS = a.YITZJYS -1
WHERE
	a.YITZJYS IS NOT NULL
	AND a.id IN (
	SELECT
		gab.CARD_ID
	FROM
		GAMS_ASSETDEPRECDETAIL_BAK0916 gab
	WHERE
		gab.JIZQJ = '202008');
--更新GAMS_CARD_CL已提折旧月数
 UPDATE
	GAMS_CARD_CL a
SET
	a.YITZJYS = a.YITZJYS -1
WHERE
	a.YITZJYS IS NOT NULL
	AND a.id IN (
	SELECT
		gab.CARD_ID
	FROM
		GAMS_ASSETDEPRECDETAIL_BAK0916 gab
	WHERE
		gab.JIZQJ = '202008');
--更新GAMS_CARD_FW已提折旧月数
 UPDATE
	GAMS_CARD_FW a
SET
	a.YITZJYS = a.YITZJYS -1
WHERE
	a.YITZJYS IS NOT NULL
	AND a.id IN (
	SELECT
		gab.CARD_ID
	FROM
		GAMS_ASSETDEPRECDETAIL_BAK0916 gab
	WHERE
		gab.JIZQJ = '202008');
--更新GAMS_CARD_JJYJZJ已提折旧月数
 UPDATE
	GAMS_CARD_JJYJZJ a
SET
	a.YITZJYS = a.YITZJYS -1
WHERE
	a.YITZJYS IS NOT NULL
	AND a.id IN (
	SELECT
		gab.CARD_ID
	FROM
		GAMS_ASSETDEPRECDETAIL_BAK0916 gab
	WHERE
		gab.JIZQJ = '202008');
	
SELECT JINGZ FROM GAMS_CARD gc WHERE gc.BILLCODE = 'TY2015000493';

SELECT JINGZ FROM GAMS_CARD_TYSB gct WHERE gct.BILLCODE = 'TY2015000493';

