SELECT * FROM GAMS_ASSETCARD ga WHERE CLASSIND NOT IN (SELECT RECID FROM GAMS_JC_ASSETCLASS);

SELECT * FROM GAMS_JC_ASSETCLASS_IND gjai ;

SELECT * FROM GAMS_CARD ga WHERE ZICFLID NOT IN (SELECT RECID FROM GAMS_JC_ASSETCLASS) ;

SELECT * FROM GAMS_CARD ga WHERE CLASSIND NOT IN (SELECT RECID FROM GAMS_JC_ASSETCLASS_IND) ;

SELECT * FROM GAMS_JC_CARDCLASS gjc WHERE RECID = '100F4A9BE5D2F5BEFBB7C8FA0883835F';

SELECT * FROM GAMS_JC_ASSETCLASS where recid = '3AD9F94460000F813316951AB4BDD594';


select billcode,zicflid,classind ,ISLASTEST from gams_assetcard WHERE classind IS NULL ;


DELETE FROM GAMS_ASSETCARD ga WHERE ga.ISLASTEST <> 1;

UPDATE  gams_assetcard SET CLASSGBID =zicflid WHERE classind IS NULL ;

select * from b0104_billdefine

SELECT * FROM GAMS_JC_ASSETCLASS_GB;

SELECT 'drop table '||table_name||' cascade constraints;' FROM USER_TABLES;

CREATE TABLE gams_card AS SELECT * FROM GAMS_ASSETCARD ga ;

SELECT ISLASTEST FROM GAMS_CARD ga WHERE ga.ISLASTEST <> 1 GROUP BY ISLASTEST;

SELECT ISLASTEST FROM GAMS_CARD WHERE BILLCODE = 'TY2019002150';

INSERT INTO GAMS_ASSETCARD (SELECT * FROM GAMS_CARD WHERE BILLCODE = 'TY2019002150');

INSERT INTO GAMS_ASSETCARD (SELECT * FROM GAMS_CARD ga WHERE CLASSIND NOT IN (SELECT RECID FROM GAMS_JC_ASSETCLASS_IND));

INSERT INTO GAMS_ASSETCARD (SELECT * FROM GAMS_CARD );

SELECT count(1),BILLCODE,YEWLX FROM GAMS_ASSETCARD ga GROUP BY BILLCODE,YEWLX ;

SELECT * FROM 

SELECT
 b.OBJECTID
FROM
 GAMS_CARD gc
LEFT JOIN (
 SELECT
  OBJECTID,
  max(gc.YEWXLH) YEWXLH
 FROM
  GAMS_CARD gc
 GROUP BY
  gc.OBJECTID) b ON
 gc.OBJECTID = b.OBJECTID AND gc.YEWXLH = b.YEWXLH WHERE b.OBJECTID IS NOT NULL AND gc.ISLASTEST  <> 1;

SELECT
 b.BILLCODE
FROM
 GAMS_ASSETCARD gc
LEFT JOIN (
 SELECT
  BILLCODE ,
  max(gc.YEWXLH) YEWXLH
 FROM
  GAMS_ASSETCARD gc
 GROUP BY
  gc.BILLCODE) b ON
 gc.BILLCODE = b.BILLCODE AND gc.YEWXLH = b.YEWXLH WHERE b.BILLCODE IS NOT NULL AND gc.ISLASTEST  <> 1;

SELECT ISLASTEST FROM GAMS_CARD gc WHERE gc.BILLCODE = 'TY2020000048';

SELECT YEWLX,ISLASTEST FROM GAMS_ASSETCARD WHERE BILLCODE IN ('YQ2016001335',
'YQ2016001336',
'TY2020000048',
'B0900004',
'TY2020000051',
'TY2020000049',
'TY2020000050',
'TY2020000052')

DELETE FROM GAMS_ASSETCARD WHERE BILLCODE IN ('YQ2016001335',
'YQ2016001336',
'TY2020000048',
'B0900004',
'TY2020000051',
'TY2020000049',
'TY2020000050',
'TY2020000052')

SELECT CLASSGBID FROM GAMS_ASSETCARD


SELECT ZICFLID FROM gams_card;

SELECT * FROM GAMS_JC_ASSETCLASS_IND gja WHERE gja.RECID = '3AD9F950400015612F8FD8803CC45284';

SELECT * FROM GAMS_JC_ASSETCLASS_GB


