SELECT * FROM gams_interface_log;

DELETE FROM gams_interface_log;

SELECT * FROM GAMS_JC_DEPARTMENT gjd ;

SELECT * FROM GAMS2_WORKFLOW_CONFIG gwc ;

DELETE FROM GAMS2_WORKFLOW_CONFIG gwc ;

SELECT * FROM GAMS_JC_FUNDNUMBER gjf WHERE XMBH  LIKE '%19SH020118%'

SELECT zhidry FROM GAMS_WITHDRAW gw 

SELECT * FROM GAMS_REIMBURSE gr WHERE gr.BILL_CODE = 'DJJZ202000009702';

SELECT * FROM gams_jc_xiaoq;

SELECT * FROM GAMS_JC_AGENCYTYPE gja 

SELECT XUEXDM FROM ORG_T_ADMIN ota ;