alter table GAMS2_WORKFLOW_DEFINITION drop column ORG_ID;
alter table GAMS2_WORKFLOW_DEFINITION add ORG_ID clob;
alter table GAMS2_WORKFLOW drop column ORG_ID;
alter table GAMS2_WORKFLOW add ORG_ID clob;
alter table GAMS2_WORKFLOW_CONFIG drop column USINGUNIT;
alter table GAMS2_WORKFLOW_CONFIG add USINGUNIT clob;


SELECT * FROM GAMS_INSPECTIONENTRY gi ;

SELECT * FROM GAMS_BILL_ANNEX gba ;

SELECT gid.SHIYR FROM GAMS_INSPECTIONENTRY gi  LEFT JOIN GAMS_INSPECTIONENTRY_DETAIL gid ON gi.id=gid.MASTER_ID WHERE gi.BILL_CODE = 'YSSZ2021000023';

SELECT * FROM NP_USER nu WHERE nu.NAME = '640000812010';

SELECT * FROM NP_PASSWORD np ;

SELECT * FROM AUTHZ_IDENTITY ai WHERE TITLE LIKE '%π‹¿Ì‘±%'

UPDATE NP_PASSWORD SET PASSWORD = 'e10adc3949ba59abbe56e057f20f883e';

SELECT * FROM GAMS_SYSTEMOPTION gs 