select * from gams_jc_cwparam WHERE title LIKE '%ÍË¿â%';
SELECT * FROM GAMS_WITHDRAW gw WHERE gw.BILL_CODE = 'TKSQ2020000008';

SELECT gwd.JIAZ ,gwd.yujsmzl FROM GAMS_WITHDRAW_DETAIL gwd WHERE gwd.MASTER_ID = '5EAB6186DA9A481489A9AF2A7DC01C0D';

SELECT gc.danj,gc.yujsmzl FROM GAMS_CARD gc WHERE BILLCODE = 'JJ2019000005' AND gc.ISLASTEST  = 1;

SELECT yujnxsmzl FROM GAMS_CARD_JJYJZJ gcj ;

SELECT gc.yujnxsmzl FROM GAMS_CARD gc;

SELECT ga.PUSHMAKE ,ga.DATASOURCE,ga.jizrq,ga.* FROM gams_withdraw ga ;

SELECT gc.yansrkdh FROM GAMS_CARD gc ;

DELETE FROM GAMS_INTERFACE_LOG;