SELECT * FROM GAMS_CARD gc ;

SELECT SHIYR FROM GAMS_CARD gc WHERE gc.BILLCODE = '20040485S';

SELECT * FROM GAMS_JC_DEPARTMENT gjd WHERE gjd.NAME = '资产管理科' OR gjd.NAME = '核算科';

SELECT * FROM GAMS_JC_DEPARTMENT gjd WHERE REPLACE(UPPER(gjd.parents) ,'-','')  LIKE (SELECT '%'|| PARENT ||'%' FROM GAMS_JC_DEPARTMENT gjd WHERE gjd.NAME = '资产管理科' );

SELECT isPermanentStaff FROM GAMS_JC_PERSONNEL gjp ;

SELECT zicgs FROM GAMS_INSPECTIONENTRY gi ;

SELECT * FROM gams_jc_biandlx gi ;


SELECT * FROM gams_jc_zicgs gjz ;

SELECT * FROM gams_jc_qcsf gjz ;

SELECT * FROM ORG o ;

SELECT * FROM ORG_T_ADMIN ota ;

6F41A6ACC0000001713C9BA0EC8CA7B7

UPDATE ORG_T_ADMIN SET PARENTS = '6F41A6ACC0000001713C9BA0EC8CA7B7';

alter table GAMS2_WORKFLOW_DEFINITION drop column ORG_ID;
alter table GAMS2_WORKFLOW_DEFINITION add ORG_ID clob;
alter table GAMS2_WORKFLOW drop column ORG_ID;
alter table GAMS2_WORKFLOW add ORG_ID clob;
alter table GAMS2_WORKFLOW_CONFIG drop column USINGUNIT;
alter table GAMS2_WORKFLOW_CONFIG add USINGUNIT clob;

SELECT * FROM GAMS_INSPECTIONENTRY gi ;

SELECT * FROM GAMS_JC_DEPARTMENT gjd WHERE id = '77D2F826800000E1A7D23690F9888844';--马克思主义学院

UPDATE GAMS_JC_DEPARTMENT b SET PARENTNAME  = (SELECT NAME FROM GAMS_JC_DEPARTMENT gjd WHERE gjd.ID = b.PARENT);
