SELECT 'drop table '||table_name||' cascade constraints;' FROM USER_TABLES;

SELECT * FROM GAMS_CARD gc ;

SELECT * FROM CQDZGCZYXY_ZCGL_TEST.GAMS_CARD_CHANGE gcc WHERE gcc.id NOT IN (SELECT ID FROM CQDZGCZYXY_ZCGL.GAMS_CARD_CHANGE);

SELECT * FROM CQDZGCZYXY_ZCGL.GAMS_CARD_CHANGE gcc WHERE gcc.ID = '6ED4E027200001810F165D68D5B2F9DE';

DELETE FROM CQDZGCZYXY_ZCGL.GAMS_CARD_CHANGE;

DROP TABLE CQDZGCZYXY_ZCGL.GAMS_CARD_CHANGE;

CREATE TABLE CQDZGCZYXY_ZCGL.GAMS_CARD_CHANGE AS SELECT * FROM CQDZGCZYXY_ZCGL.GAMS_CARD_CHANGE_TEMP gcct ;

DELETE CQDZGCZYXY_ZCGL.GAMS_CARD_CHANGE WHERE id IN (SELECT id FROM CQDZGCZYXY_ZCGL_TEST.GAMS_CARD_CHANGE);

INSERT INTO CQDZGCZYXY_ZCGL.GAMS_CARD_CHANGE VALUES  (SELECT * FROM CQDZGCZYXY_ZCGL_TEST.GAMS_CARD_CHANGE);
