SELECT * FROM NP_PASSWORD np ;

UPDATE NP_PASSWORD SET PASSWORD = '$2a$10$Czl7GVERdyM0VhY/lxRU6OgTUN6aychGpIBrwgK841m13kuR1gvZC';

SELECT * FROM GAMS2_WORKFLOW_BUS_PROCESS gwbp ;

SELECT * FROM GAMS_BIZ_CONFIG;

