SELECT
--card.*
sum(card.LEIJZJ)
FROM
	gams_card card
JOIN (
	SELECT
		c.objectid AS objectid,
		max(c.yewxlh) AS yewxlh
	FROM
		gams_card c
	GROUP BY
		c.objectid) temp ON
	card.objectid = temp.objectid
LEFT JOIN (
	SELECT
		detail.CARD_OBJ_ID AS cardobjectid,
		sum(detail.zhejje) AS leijzj
	FROM
		GAMS_ASSETDEPRECDETAIL detail
	GROUP BY
		detail.CARD_OBJ_ID) ljzj ON
	card.objectid = ljzj.cardobjectid
WHERE
	card.auditstate = 2
	AND card.CARDSTATE LIKE '0%'
	AND card.yewxlh = temp.yewxlh
	AND card.SORTGB = '3711F0FCC0000001BFFFD450E0E1A606' 
	
	AND card.id NOT IN (
SELECT gc.ID FROM GAMS_CARD gc LEFT JOIN GAMS_JC_ASSETSORT_GB gjag ON gc.SORTGB = gjag.ID WHERE gjag.NAME = '01' AND gc.ISLASTEST =1 AND gc.CARDSTATE LIKE '0%' AND gc.AUDITSTATE = 2)

	


SELECT sum(zhejje) FROM GAMS_ASSETDEPRECDETAIL  WHERE SRC_BILL_DEFINE = 'com.jiuqi.np.gams2.depreciation.AssetDepreciationInitBill' OR SRC_BILL_DEFINE  = 'com.jiuqi.np.gams2.depreciation.AssetDepreciationModifyBill' AND jizqj <= 202010;

SELECT SRC_BILL_DEFINE FROM GAMS_ASSETDEPRECDETAIL  GROUP BY  SRC_BILL_DEFINE ;

SELECT count(1) FROM GAMS_ASSETDEPRECDETAIL WHERE JIZQJ <=201901;

SELECT * FROM GAMS_ASSETDEPREC_I;

SELECT * FROM GAMS_ASSETDEPREC_H;

SELECT
	ga.ZHEJJE ,
	a.leijzj
FROM
	GAMS_ASSETDEPRECDETAIL ga
LEFT JOIN (
	SELECT
		CARD_ID ,
		leijzj
	FROM
		GAMS_ASSETDEPREC_I gai
	LEFT JOIN GAMS_ASSETDEPREC_H gah ON
		gai.MASTER_ID = gah.ID
	WHERE
		gah.JIZQJ = '201901') a ON
	a.card_id <> ga.CARD_ID
WHERE
	ga.JIZQJ = '201812'
--	AND a.leijzj - ga.ZHEJJE > 1
--	AND ga.ZHEJJE < a.leijzj
--	AND a.leijzj IS NOT NULL
--	AND ga.ZHEJJE IS NOT NULL ;
--32,946


SELECT * FROM GAMS_ASSETDEPREC_I gai LEFT JOIN GAMS_ASSETDEPREC_H gah ON gai.MASTER_ID = gah.ID  WHERE gah.JIZQJ = '201901';--19,454



CREATE TABLE GAMS_ASSETDEPREC_I_1224 AS SELECT * FROM GAMS_ASSETDEPREC_I;
CREATE TABLE GAMS_ASSETDEPREC_H_1224 AS SELECT * FROM GAMS_ASSETDEPREC_H;
CREATE TABLE GAMS_ASSETDEPRECDETAIL_1224 AS SELECT * FROM GAMS_ASSETDEPRECDETAIL;

SELECT count(1),sum(JIAZ),sum(LEIJZJ) FROM GAMS_CARD gc LEFT JOIN GAMS_JC_ASSETSORT_GB gjag ON gc.SORTGB = gjag.ID WHERE gjag.NAME = '01' AND gc.ISLASTEST =1 AND gc.CARDSTATE LIKE '0%' AND gc.AUDITSTATE = 2;

SELECT * FROM GAMS_JC_ASSETSORT_GB;
726636936.19
726636936.19	170396522.97

SELECT DISTINCT gc.YEWXLH FROM GAMS_CARD gc 

SELECT *FROM ORG o2 ;

SELECT * FROM GAMS_ASSETDEPRECDETAIL ;

SELECT * FROM GAMS_ASSETDEPRECDETAIL WHERE COMMENTS  = '折旧信息初始化';

SELECT gc.BILLCODE ,gc.LEIJZJ, h.a FROM GAMS_CARD gc LEFT JOIN (SELECT detail.CARD_OBJ_ID,sum(detail.zhejje) AS a  FROM  GAMS_ASSETDEPRECDETAIL detail GROUP BY detail.CARD_OBJ_ID)  h ON  gc.OBJECTID = h.CARD_OBJ_ID WHERE gc.LEIJZJ = 0 AND  h.a = 931.71;


SELECT sum(gc.LEIJZJ-h.a) AS b FROM GAMS_CARD gc LEFT JOIN (SELECT detail.CARD_OBJ_ID,sum(detail.zhejje) AS a  FROM  GAMS_ASSETDEPRECDETAIL detail GROUP BY detail.CARD_OBJ_ID)  h ON  gc.OBJECTID = h.CARD_OBJ_ID WHERE gc.LEIJZJ <> h.a;
SELECT * FROM gams_jc_deprecstate;
SELECT * FROM GAMS_CARD gc WHERE gc.LEIJZJ = 0 AND gc. zhejzt = '36B91BD280000021539773C770101723';

SELECT * FROM GAMS_CARD gc WHERE gc.BILLCODE = 'TY2019000353' AND gc.ORGUNIT ='6E35BC1F80000001F6D62BD49F8EC9CC';

SELECT * FROM GAMS_ASSETDEPRECDETAIL WHERE CARD_OBJ_ID = '968A5A72C3EF460C86B6D08E649660CE';

SELECT sum(ZHEJJE) FROM GAMS_ASSETDEPRECDETAIL 
