alter table GAMS2_WORKFLOW_DEFINITION drop column ORG_ID;
alter table GAMS2_WORKFLOW_DEFINITION add ORG_ID clob;
alter table GAMS2_WORKFLOW drop column ORG_ID;
alter table GAMS2_WORKFLOW add ORG_ID clob;
alter table GAMS2_WORKFLOW_CONFIG drop column USINGUNIT;
alter table GAMS2_WORKFLOW_CONFIG add USINGUNIT clob;

SELECT * FROM GAMS_INSPECTIONENTRY gi WHERE gi.ID = '1C4F702957AD464488B8ED0A9C51C0F5';

DELETE  FROM GAMS2_WORKFLOW_COMMON_TASK gwct WHERE gwct.BUSINESS_DATA_ID = '2151C58A9B9B4055AB36ED3362DDDD20';

SELECT gc.BILLCODE FROM GAMS_ACCEPTANCEUSE ga LEFT JOIN GAMS_CARD gc ON ga.CARDID = gc.ID WHERE ga.LINGYZT = 0 AND gc.BILLCODE IS NOT NULL ;

SELECT * FROM GAMS_CARD gc WHERE gc.ID = 'FA70D734D1FD4B2F818BCE6254475993';

DELETE FROM GAMS_ACCEPTANCEUSE ga WHERE ga.CARDID NOT IN (SELECT id FROM GAMS_CARD gc) AND ga.BILLDEFINE = 'com.jiuqi.np.gams2.business.bill.InspectionEntryBillDefine';

SELECT gc.OBJECTID FROM GAMS_ACCEPTANCEUSE ga LEFT JOIN GAMS_CARD gc ON ga.CARDID = gc.ID WHERE  ga.BILLDEFINE = 'com.jiuqi.np.gams2.business.bill.InspectionEntryBillDefine' AND ga.LINGYZT = 0 AND gc.OBJECTID IS NULL ;

