
	SELECT
	
		CASE WHEN CWHSTSDM = '07' THEN '专利权'
		WHEN CWHSTSDM = '08' THEN '商标权'
		WHEN CWHSTSDM = '09' THEN '著作权'
		WHEN CWHSTSDM = '10' THEN '非专利技术'
		WHEN CWHSTSDM = '11' THEN '其他无形资产'
	END AS zicfl FROM TC_TEMP tt GROUP BY CWHSTSDM;