SELECT * FROM GAMS_ASSETDISPOSEAPP ga ;

SELECT
	gad.SHIYBMID ,
	gad.shiybmmc ,
	gad.*
FROM
	GAMS_ASSETDISPOSEAPP_DETAIL gad
WHERE
	gad.MASTER_ID = (
	SELECT
		id
	FROM
		GAMS_ASSETDISPOSEAPP ga
	WHERE
		ga.BILL_CODE = 'XWCZSQ2020000017');

SELECT * FROM gams_jc_department gjd 

SELECT GC.SHIYBM ,GC.* FROM GAMS_CARD gc WHERE gc.BILLCODE = 'QD00123'

SELECT * FROM  GAMS_JC_DEPARTMENT gjp ;

SELECT * FROM GAMS_JC_DEPOSITARY gjd ;

SELECT * FROM 