SELECT * FROM GAMS_ASSETCARD ga WHERE CLASSIND NOT IN (SELECT RECID FROM GAMS_JC_ASSETCLASS);

SELECT * FROM GAMS_JC_CARDCLASS gjc WHERE RECID = '100F4A9BE5D2F5BEFBB7C8FA0883835F';

SELECT * FROM GAMS_JC_ASSETCLASS where recid = '3AD9F94460000F813316951AB4BDD594';


select billcode,zicflid,classind ,ISLASTEST from gams_assetcard WHERE classind IS NULL ;


DELETE FROM GAMS_ASSETCARD ga WHERE ga.ISLASTEST <> 1;

select * from b0104_billdefine

SELECT * FROM GAMS_JC_ASSETCLASS_GB;

SELECT 'drop table '||table_name||' cascade constraints;' FROM USER_TABLES;

CREATE TABLE gams_card AS SELECT * FROM GAMS_ASSETCARD ga ;
