SELECT * FROM AUTHZ_IDENTITY ai ;

SELECT * FROM NP_USER nu ;


SELECT * FROM  NP_USER;
SELECT * FROM  NP_PASSWORD;
SELECT * FROM  AUTHZ_IDENTITY;
SELECT * FROM  GAMS_USER_ORG_REL ;
SELECT * FROM  AUTHZ_USER_IDENTITY;
SELECT * FROM  AUTHZ_IDENTITY_ROLE WHERE IDENTITY_ID  = '0E005F1D6A2644E5B5D9710B69693623';
SELECT * FROM  AUTHZ_RULE_AUTHORIZATION;
SELECT * FROM  GAMS_JC_PERSONNEL;
SELECT * FROM AUTHZ_IDENTITY_ROLE WHERE ROLE_ID = '26CF879021C24C71BF2C4CF9B0868BE8';

INSERT INTO AUTHZ_RULE_AUTHORIZATION a SELECT * FROM AUTHZ_RULE_AUTHORIZATION_temp b where b.grantee_id not in (select c.grantee_id  from AUTHZ_RULE_AUTHORIZATION c left join AUTHZ_RULE_AUTHORIZATION_temp d on c.grantee_id = d.grantee_id);

SELECT * FROM AUTHZ_IDENTITY ai WHERE ai.ID = '8B11DB48910F424E9995A3BC91FB3166';

SELECT * FROM AUTHZ_ROLE ar ;

SELECT * FROM AUTHZ_IDENTITY WHERE NAME = 'admin'

DELETE FROM AUTHZ_RULE_AUTHORIZATION WHERE ACCESS_RANTOR = '8B11DB48910F424E9995A3BC91FB3166';


CREATE TABLE AUTHZ_RULE_AUTHORIZATION_0310 AS SELECT * FROM AUTHZ_RULE_AUTHORIZATION 

SELECT * FROM NP_PASSWORD np WHERE USERNAME = 'admin1'

SELECT * FROM AUTHZ_IDENTITY_ROLE WHERE IDENTITY_ID = '8B11DB48910F424E9995A3BC91FB3166';

SELECT A.constraint_name, A.table_name, b.constraint_name
  FROM user_constraints A, user_constraints b
 WHERE A.constraint_type = 'R'
   AND b.constraint_type = 'P'
   AND A.r_constraint_name = b.constraint_name
   AND A.constraint_name = UPPER('FKHOEX80W79C481E7LKO3FMPYWG');

  DELETE FROM GAMS_USER_LASTLOGIN gul 
  SELECT 'drop table '||table_name||' cascade constraints;' FROM USER_TABLES;

 SELECT * FROM AUTHZ_IDENTITY ai WHERE ai.ID = '8B11DB48910F424E9995A3BC91FB3166';
 SELECT * FROM AUTHZ_IDENTITY ai WHERE ai.ID = '668E1827AA86414F92C39D62F437321E';

SELECT * FROM AUTHZ_IDENTITY ai WHERE ai.NAME = 'i_220061027_ZCGLY_220061027';

SELECT * FROM NP_USER nu WHERE NAME = 'admin';

SELECT * FROM AUTHZ_USER_IDENTITY aui WHERE USER_ID  = 'FFFFFFFFFFFFFFFFCCCCFFFFFFFFFFFF' ;

SELECT * FROM user gus guor WHERE USERID =  'FFFFFFFFFFFFFFFFCCCCFFFFFFFFFFFF';

DELETE FROM GAMS_USER_SIGNATURE;

DELETE FROM GAMS_USER_LASTLOGIN gul 

SELECT * FROM GAMS_USER_LASTLOGIN gul WHERE USERID  = 'FFFFFFFFFFFFFFFFCCCCFFFFFFFFFFFF';

SELECT * FROM NP_USER nu WHERE id = '757804E20000036159930B1099D71E26';

SELECT gi.ZICFL FROM GAMS_INSPECTIONENTRY gi 

SELECT * FROM GAMS_CARD_OUTLAY gco WHERE MASTER_ID = '351E033FAD9C43B1B1D48717A9736E32';

SELECT * FROM GAMS_JC_FUNDNUMBER gjf WHERE code = '7001006007002';

SELECT * FROM GAMS_INSPECTIONENTRY_DETAIL gid 

SELECT * FROM gams_card WHERE REBILLID = 'EC904E6C48BD40F893E642CEC30FEF52';
SELECT * FROM gams_jc_depositary gjd ;

SELECT * FROM GAMS_PEIZBZ_PARAM_ADMIN_DETAIL;

SELECT * FROM gams_jc_orginfo_config_jy;

DROP TABLE GAMS_PEIZBZ_PARAM_ADMIN_DETAIL;

SELECT carddefinename FROM gams_jc_assetclass GROUP BY carddefinename;

SELECT * FROM GAMS2_WORKFLOW_CONFIG gwc ;

select userenv('language') from dual;

select * from nls_database_parameters

alter table GAMS2_WORKFLOW_DEFINITION drop column ORG_ID;
alter table GAMS2_WORKFLOW_DEFINITION add ORG_ID clob;
alter table GAMS2_WORKFLOW drop column ORG_ID;
alter table GAMS2_WORKFLOW add ORG_ID clob;
alter table GAMS2_WORKFLOW_CONFIG drop column USINGUNIT;
alter table GAMS2_WORKFLOW_CONFIG add USINGUNIT clob;

SELECT 'drop table '||table_name||' cascade constraints;' FROM USER_TABLES;
SELECT * FROM NP_PASSWORD np ;

UPDATE NP_PASSWORD SET PASSWORD = 'e10adc3949ba59abbe56e057f20f883e';

SELECT * FROM bum_mid;

SELECT * FROM jiaozg_mid;

SELECT * FROM mid;

SELECT * FROM GAMS_JC_PERSONNEL gjp ;

SELECT * FROM GAMS_ASSETCARD ga 

SELECT * FROM md_org;

SELECT * FROM GAMS_ASSETCARD ga ;

DELETE FROM GAMS_CARD;

DROP TABLE GAMS_CARD;

CREATE TABLE GAMS_CARD_t AS SELECT * FROM GAMS_CARD gc WHERE 1=2;

CREATE TABLE GAMS_CARD AS SELECT * FROM GAMS_CARD_t gc WHERE 1=2;

SELECT count(1) FROM GAMS_CARD gcj ;

SELECT * FROM GAMS_CARD_TYSB gct ;

update gams_unitdatatrans_detail l set l.isfinishtrans=0;

SELECT * FROM GAMS_JC_PERSONNEL gjp 

SELECT * FROM GAMS_JC_DEPARTMENT gjd ;

select count(*) from v$session;

SELECT * FROM GAMS_JC_ASSETCLASS gja WHERE gja.ID = '3AD9F950400015612F8FD8803CC45284';

SELECT * FROM GAMS_JC_ASSETCLASS gjc WHERE id = '100F4A9BE5D2F5BEFBB7C8FA0883835F';

SELECT DETAIL_TABLE FROM GAMS_JC_ASSETCLASS gja GROUP BY DETAIL_TABLE;

SELECT * FROM GAMS_JC_ASSETCLASS_IND a WHERE a.id NOT IN (SELECT recid FROM GX3.GAMS_JC_ASSETCLASS);

SELECT * FROM GX3.GAMS_JC_ASSETCLASS a WHERE a.RECID NOT IN (SELECT id FROM GAMS_JC_ASSETCLASS_IND);


SELECT * FROM GAMS_JC_ASSETCLASS a WHERE a.id NOT IN (SELECT recid FROM GX3.GAMS_JC_ASSETCLASS_GB);

SELECT * FROM GX3.GAMS_JC_ASSETCLASS a WHERE a.RECID NOT IN (SELECT id FROM GAMS_JC_ASSETCLASS_IND);

SELECT * FROM GAMS_JC_ASSETCLASS a WHERE a.id NOT IN (SELECT recid FROM GX3.GAMS_JC_ASSETCLASS_GB);

SELECT * FROM GX3.GAMS_JC_ASSETCLASS_GB a WHERE a.RECID NOT IN (SELECT id FROM GAMS_JC_ASSETCLASS);




SELECT * FROM GAMS_JC_ASSETCLASS_IND a WHERE a.id NOT IN (SELECT recid FROM CQDZGCZYXYZCGL.GAMS_JC_ASSETCLASS);

SELECT * FROM CQDZGCZYXYZCGL.GAMS_JC_ASSETCLASS a WHERE a.RECID NOT IN (SELECT id FROM GAMS_JC_ASSETCLASS_IND);

SELECT * FROM GAMS_JC_ASSETCLASS;

DELETE FROM GAMS_JC_ASSETCLASS_IND a WHERE a.id NOT IN (SELECT recid FROM GX3.GAMS_JC_ASSETCLASS);

DELETE FROM GX3.GAMS_JC_ASSETCLASS a WHERE a.RECID NOT IN (SELECT id FROM GAMS_JC_ASSETCLASS_IND);

SELECT * FROM GAMS_JC_ASSETCLASS;

DELETE FROM gams_jc_assetclass;

SELECT * FROM gams_jc_assetclass WHERE id = '66c9497b-4000-0001-e4cf-a40edd125e59';

SELECT * FROM GAMS_CARD_JJYJZJ;

select count(c.ID),sum(c.shul),sum(c.jiaz)
  from GAMS_CARD c
  where 1=1
  
  and c.ISLASTEST = 1
  and c.CARDSTATE like '0%'
  and c.auditstate='2'
  
  