SELECT * FROM AUTHZ_IDENTITY ai ;

SELECT * FROM NP_USER nu ;


SELECT * FROM  NP_USER;
SELECT * FROM  NP_PASSWORD;
SELECT * FROM  AUTHZ_IDENTITY;
SELECT * FROM  GAMS_USER_ORG_REL ;
SELECT * FROM  AUTHZ_USER_IDENTITY;
SELECT * FROM  AUTHZ_IDENTITY_ROLE WHERE IDENTITY_ID  = '0E005F1D6A2644E5B5D9710B69693623';
SELECT * FROM  AUTHZ_RULE_AUTHORIZATION;
SELECT * FROM  GAMS_JC_PERSONNEL;
SELECT * FROM AUTHZ_IDENTITY_ROLE WHERE ROLE_ID = '26CF879021C24C71BF2C4CF9B0868BE8';

INSERT INTO AUTHZ_RULE_AUTHORIZATION a SELECT * FROM AUTHZ_RULE_AUTHORIZATION_temp b where b.grantee_id not in (select c.grantee_id  from AUTHZ_RULE_AUTHORIZATION c left join AUTHZ_RULE_AUTHORIZATION_temp d on c.grantee_id = d.grantee_id);

SELECT * FROM AUTHZ_IDENTITY ai WHERE ai.ID = '8B11DB48910F424E9995A3BC91FB3166';

SELECT * FROM AUTHZ_ROLE ar ;

SELECT * FROM AUTHZ_IDENTITY WHERE NAME = 'admin'

DELETE FROM AUTHZ_RULE_AUTHORIZATION WHERE ACCESS_RANTOR = '8B11DB48910F424E9995A3BC91FB3166';


CREATE TABLE AUTHZ_RULE_AUTHORIZATION_0310 AS SELECT * FROM AUTHZ_RULE_AUTHORIZATION 

SELECT * FROM NP_PASSWORD np WHERE USERNAME = 'admin1'

SELECT * FROM AUTHZ_IDENTITY_ROLE WHERE IDENTITY_ID = '8B11DB48910F424E9995A3BC91FB3166';

SELECT A.constraint_name, A.table_name, b.constraint_name
  FROM user_constraints A, user_constraints b
 WHERE A.constraint_type = 'R'
   AND b.constraint_type = 'P'
   AND A.r_constraint_name = b.constraint_name
   AND A.constraint_name = UPPER('FKHOEX80W79C481E7LKO3FMPYWG');

  DELETE FROM GAMS_USER_LASTLOGIN gul 
  SELECT 'drop table '||table_name||' cascade constraints;' FROM USER_TABLES;

 SELECT * FROM AUTHZ_IDENTITY ai WHERE ai.ID = '8B11DB48910F424E9995A3BC91FB3166';
 SELECT * FROM AUTHZ_IDENTITY ai WHERE ai.ID = '0E005F1D6A2644E5B5D9710B69693623';

SELECT * FROM AUTHZ_IDENTITY ai WHERE ai.NAME = 'i_220061027_ZCGLY_220061027';

SELECT * FROM NP_USER nu WHERE NAME = 'admin';

SELECT * FROM AUTHZ_USER_IDENTITY aui WHERE USER_ID  = 'FFFFFFFFFFFFFFFFCCCCFFFFFFFFFFFF' ;

SELECT * FROM user gus guor WHERE USERID =  'FFFFFFFFFFFFFFFFCCCCFFFFFFFFFFFF';

DELETE FROM GAMS_USER_SIGNATURE

SELECT * FROM NP_USER nu WHERE id = '757804E20000036159930B1099D71E26';

