SELECT * FROM GAMS_ASSETDISPOSEAPP ga ;

SELECT
	gad.SHIYBMID ,
	gad.*
FROM
	GAMS_ASSETDISPOSEAPP_DETAIL gad
WHERE
	gad.MASTER_ID = (
	SELECT
		id
	FROM
		GAMS_ASSETDISPOSEAPP ga
	WHERE
		ga.BILL_CODE = 'XWCZSQ2020000017');

SELECT * FROM gams_jc_department gjd ;

SELECT
	gad.SHIYBMID ,
	gad.shiybmmc,
	gad.*
FROM
	GAMS_ASSETDISPOSEAPP_DETAIL gad
	LEFT JOIN GAMS_ASSETDISPOSEAPP ga ON ga.id = gad.MASTER_ID 
	WHERE ga.BILL_CODE = 'XWCZSQ2020000019';

SELECT * FROM gams_jc_department gjd ;