SELECT * FROM NP_PASSWORD gc 

UPDATE NP_PASSWORD SET PASSWORD = 'e10adc3949ba59abbe56e057f20f883e';

DELETE FROM GAMS_USER_LASTLOGIN gul 

DELETE FROM GAMS_USER_LOGIN_POLICY gulp 

alter table GAMS2_WORKFLOW_DEFINITION drop column ORG_ID;
alter table GAMS2_WORKFLOW_DEFINITION add ORG_ID clob;
alter table GAMS2_WORKFLOW drop column ORG_ID;
alter table GAMS2_WORKFLOW add ORG_ID clob;
alter table GAMS2_WORKFLOW_CONFIG drop column USINGUNIT;
alter table GAMS2_WORKFLOW_CONFIG add USINGUNIT clob;

SELECT * FROM gams_jc_assetclass WHERE TITLE = 'º½¿ÕÒÇÆ÷';--386f082a-4000-1421-24f8-accc809d5fb5

SELECT ZICGS FROM GAMS_CARD_TYSB gct 