SELECT 'drop table '||table_name||' cascade constraints;' FROM USER_TABLES;

SELECT * FROM GAMS_JC_ASSETSORT_GB gjag ;

SELECT * FROM GAMS_CARD gc ;

SELECT * FROM GAMS_ASSETCARD ga ;

SELECT * FROM BIZ_ZY001_BTCJ_H;



SELECT * FROM GD_1130;

SELECT * FROM GAMS_ASSETTURNOVER_H ;

CREATE TABLE BIZ_ZY001_BTCJ_H AS SELECT * FROM JLTDXY.BIZ_ZY001_BTCJ_H WHERE 1=2;--不提冲减

CREATE TABLE  GAMS_ASSETTURNOVER_H AS SELECT * FROM JLTDXY.GAMS_ASSETTURNOVER_H WHERE 1=2;--收益上缴
CREATE TABLE  GAMS_ASSETTURNOVER_I AS SELECT * FROM JLTDXY.GAMS_ASSETTURNOVER_I WHERE 1=2;


CREATE TABLE  GAMS_ASSETINCOME_H AS SELECT * FROM JLTDXY.GAMS_ASSETINCOME_H WHERE 1=2;--收益登记
CREATE TABLE  GAMS_ASSETINCOME_I AS SELECT * FROM JLTDXY.GAMS_ASSETINCOME_I WHERE 1=2;

update gams_unitdatatrans_detail l set l.isfinishtrans=0;

SELECT * FROM GAMS_JC_PERSONNEL;

SELECT * FROM GAMS_CARD;

SELECT * FROM GAMS_JC_COMFIRMSTATUS;

SELECT count(1) FROM GAMS_ASSETCARD ga ;

SELECT * FROM GAMS2_WORKFLOW_CONFIG gwc ;

SELECT * FROM GAMS_CARD gc ;

SELECT * FROM GAMS_SYSTEMOPTION gs ;

DROP TABLE BIZ_ZY001_BTCJ_H;
DROP TABLE GAMS_ASSETTURNOVER_H;
DROP TABLE GAMS_ASSETTURNOVER_I;
DROP TABLE GAMS_ASSETINCOME_H;
DROP TABLE GAMS_ASSETINCOME_I;

select count(d.recid),sum(d.shul),sum(d.jiaz)
from GAMS_ASSETCARd d
where 1 = 1 
and d.ISLASTEST = 1
and d.CARDSTATE like '0%'
and d.auditstate='2'
and d.ORGUNIT in (hextoraw('3BF21B77800000012572D58D9D07A1FF'));
216156	16661770	4388938036.13041
SELECT * FROM MD_ORG mo ;

SELECT * FROM GAMS_JC_ASSETSORT_GB gjag ;

select count(c.ID),sum(c.shul),sum(c.jiaz)
  from GAMS_CARD c
  where 1=1
  and c.SHIXRQ > systimestamp 
  AND c.SORTGB = '3711F2B38000000196D90238154FE14D'
  and c.ORGUNIT = hextoraw('3BF21B77800000012572D58D9D07A1FF')
  and c.ISLASTEST = 1
  and c.CARDSTATE like '0%'
  and c.auditstate='2';
  
  SELECT * FROM ORG o ;
  
 
 SELECT * FROM GAMS_ASSETCARD ga WHERE ga.SORTGBID 
 
select count(d.recid),sum(d.shul),sum(d.jiaz)
from GAMS_ASSETCARd d
where 1 = 1 
AND d.SORTGBID  = hextoraw('3711F2B38000000196D90238154FE14D')
and d.ISLASTEST = 1
and d.CARDSTATE like '0%'
and d.auditstate='2'
and d.ORGUNIT in (hextoraw('3BF21B77800000012572D58D9D07A1FF'));--专用

216156	16661770	4388938036.13041
SELECT * FROM MD_ORG mo ;

SELECT * FROM GAMS_JC_ASSETSORT_GB gjag ;

SELECT * FROM GAMS_ASSETCARD ga WHERE ga.BILLCODE = 'JJ2021000356';