INSERT INTO NP_USER a SELECT * FROM NP_USER_temp b where b.id not in (select c.id  from np_user c left join np_user_temp d on c.id = d.id);
INSERT INTO NP_PASSWORD a SELECT * FROM NP_PASSWORD_temp b where b.id not in (select c.id  from NP_PASSWORD c left join NP_PASSWORD_temp d on c.USERNAME = d.USERNAME);
INSERT INTO AUTHZ_IDENTITY a SELECT * FROM AUTHZ_IDENTITY_temp b where b.id not in (select c.id  from AUTHZ_IDENTITY c left join AUTHZ_IDENTITY_temp d on c.NAME = d.NAME);
INSERT INTO GAMS_USER_ORG_REL a SELECT * FROM GAMS_USER_ORG_REL_temp b where b.id not in (select c.id  from GAMS_USER_ORG_REL c left join GAMS_USER_ORG_REL_temp d on c.USERID = d.USERID);
INSERT INTO AUTHZ_USER_IDENTITY a SELECT * FROM AUTHZ_USER_IDENTITY_temp b where b.id not in (select c.id  from AUTHZ_USER_IDENTITY c left join AUTHZ_USER_IDENTITY_temp d on c.USER_ID = d.USER_ID);
INSERT INTO AUTHZ_IDENTITY_ROLE a SELECT * FROM AUTHZ_IDENTITY_ROLE_temp b where b.IDENTITY_ID not in (select c.IDENTITY_ID  from AUTHZ_IDENTITY_ROLE c left join AUTHZ_IDENTITY_ROLE_temp d on c.IDENTITY_ID = d.IDENTITY_ID);
INSERT INTO AUTHZ_RULE_AUTHORIZATION a SELECT * FROM AUTHZ_RULE_AUTHORIZATION_temp b where b.grantee_id not in (select c.grantee_id  from AUTHZ_RULE_AUTHORIZATION c left join AUTHZ_RULE_AUTHORIZATION_temp d on c.grantee_id = d.grantee_id);
update GAMS_JC_PERSONNEL  a set a.USERID = (SELECT b.USERID FROM GAMS_JC_PERSONNEL_TEMP b WHERE a.ID= b.ID ) WHERE a.USERID IS null;

SELECT * FROM GAMS_JC_PERSONNEL WHERE code = 'ZN';

SELECT * FROM GAMS_JC_PERSONNEL WHERE NAME = '张宁';	8922CBC755C34C20993244E1B30BBEDC

FA6860444A1144B38A2AE6B882C56FD5
SELECT * FROM GAMS_JC_DEPARTMENT gjd WHERE gjd.ID = '77D2F825A0000081C704749F93FDD0C2';

SELECT COUNT(1),USERID FROM GAMS_JC_PERSONNEL GROUP BY USERID ORDER BY COUNT(1) DESC ;

SELECT 'drop table '||table_name||' cascade constraints;' FROM USER_TABLES;

SELECT * FROM GAMS_JC_PERSONNEL gjp WHERE CODE = '20102479';

SELECT * FROM AUTHZ_USER_IDENTITY aui ;

SELECT * FROM GAMS_JC_PERSONNEL gjp WHERE NAME = '李那日苏';

SELECT * FROM NP_USER nu WHERE nu.NICKNAME = '李那日苏';

SELECT count(1),NAME FROM GAMS_JC_PERSONNEL GROUP BY NAME  ORDER BY COUNT(1) DESC ;






