CREATE TABLE GAMS_CARD_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD;
CREATE TABLE GAMS_CARD_CL_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_CL gcc ;
CREATE TABLE GAMS_CARD_FW_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_FW gcf ;
CREATE TABLE GAMS_CARD_GZW_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_GZW gcg ;
CREATE TABLE GAMS_CARD_JJYJZJ_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_JJYJZJ gcj ;
CREATE TABLE GAMS_CARD_TD_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_TD gct ;
CREATE TABLE GAMS_CARD_TSDA_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_TSDA gct ;
CREATE TABLE GAMS_CARD_TYSB_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_TYSB gct ;
CREATE TABLE GAMS_CARD_TZDZW_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_TZDZW gct ;
CREATE TABLE GAMS_CARD_WWHCLP_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_WWHCLP gcw ;
CREATE TABLE GAMS_CARD_WXZC_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_WXZC gcw ;
CREATE TABLE GAMS_CARD_ZYSB_bak1217 AS SELECT id ,YUJSMZL FROM GAMS_CARD_ZYSB gcz ;

DELETE FROM GAMS_CARD;
DELETE FROM GAMS_CARD_CL;
DELETE FROM GAMS_CARD_FW;
DELETE FROM GAMS_CARD_GZW;
DELETE FROM GAMS_CARD_JJYJZJ;
DELETE FROM GAMS_CARD_TD;
DELETE FROM GAMS_CARD_TSDA;

DELETE FROM GAMS_CARD_TYSB;
DELETE FROM GAMS_CARD_TZDZW;
DELETE FROM GAMS_CARD_WWHCLP;
DELETE FROM GAMS_CARD_ZYSB;
DELETE FROM GAMS_CARD_WXZC;
DELETE FROM GAMS_CARD_TD;
DELETE FROM GAMS_CARD_TSDA;


SELECT * FROM GAMS_JC_ASSETSORT_GB gjag ;39717244-8000-0021-7d39-6956c4cd77a6

SELECT * FROM GAMS_JC_ASSETCLASS gjag ;

DELETE FROM GAMS_JC_ASSETSORT_GB;
DELETE FROM GAMS_JC_ASSETCLASS;
DELETE FROM GAMS_JC_ASSETCLASS_GB;
DELETE FROM GAMS_JC_ASSETCLASS_IND;

SELECT * FROM NP_USER nu ;

SELECT * FROM GAMS_CARD;

SELECT * FROM GAMS_ASSETCHANGE_DETAIL ga ;

SELECT 'drop table '||table_name||' cascade constraints;' FROM USER_TABLES;


SELECT A.constraint_name, A.table_name, b.constraint_name
  FROM user_constraints A, user_constraints b
 WHERE A.constraint_type = 'R'
   AND b.constraint_type = 'P'
   AND A.r_constraint_name = b.constraint_name
   AND A.constraint_name = UPPER('FKUK2O7ICTBN9OGDVGIARKYY4L')
   
select constraint_name,constraint_type,table_name from all_constraints where CONSTRAINT_NAME='SYS_C00292847';

GAMS_TRANSFER		GAMS_JC_PERSONNEL
GAMS_INNERDISPREG	GAMS_JC_PERSONNEL
GAMS_ASSETDISPOSEREG_DETAIL	GAMS_JC_DEPARTMENT
GAMS_INSPECTIONENTRY	GAMS_JC_DEPARTMENT
GAMS_INSPECTIONENTRY_DETAIL		GAMS_JC_PERSONNEL

SELECT* FROM GAMS_JC_PERSONNEL gjp ;

SELECT HANGYFL FROM GAMS_CARD gc WHERE gc.BILLCODE = '0600001A';

SELECT ZICFLID FROM GX3.GAMS_ASSETCARD ga WHERE ga.BILLCODE = '0600001A';


SELECT * FROM GX3.GAMS_JC_ASSETCLASS WHERE RECID = '3AD9F950E0000041E7CBB548933E0D22';

SELECT * FROM GAMS_JC_ASSETCLASS_IND WHERE id = '3AD9F950E0000041E7CBB548933E0D22';





SELECT HANGYFL FROM GAMS_CARD gc WHERE gc.BILLCODE = 'TY2017004219';--3ad9f951-4000-0321-1b2d-0fd5bfe024c5

SELECT ZICFLID FROM CQDZGCZYXYZCGL.GAMS_ASSETCARD ga WHERE ga.BILLCODE = 'TY2017004219';--3ad9f951-4000-0321-1b2d-0fd5bfe024c5


SELECT * FROM CQDZGCZYXYZCGL.GAMS_JC_ASSETCLASS WHERE RECID = '3AD9F951400003211B2D0FD5BFE024C5';

SELECT * FROM GAMS_JC_ASSETCLASS_IND WHERE id = '3AD9F951400003211B2D0FD5BFE024C5';


SELECT * FROM GAMS_JC_ASSETCLASS_IND WHERE name = '04200207';--3ad9f943-e000-08c1-1bc0-56642fd45744

SELECT * FROM GAMS_JC_ASSETCLASS_BAK WHERE STDCODE = '04200207';




select constraint_name,constraint_type,table_name from all_constraints where CONSTRAINT_NAME='SYS_C00292847';

