CREATE TABLE cw_bmzd (
	ztdm VARCHAR (20) NOT NULL,
	bmbh VARCHAR (20) NOT NULL,
	bmmc VARCHAR (255) NULL,
	CONSTRAINT PK_cw_bmzd PRIMARY KEY (ztdm, bmbh)
);

CREATE TABLE cw_dwzd (
	ztdm VARCHAR (20) NOT NULL,
	dwbh VARCHAR (30) NOT NULL,
	dwmc VARCHAR (200) NULL,
	khh VARCHAR (200) NULL,
	bank VARCHAR (20) NULL,
	yhzh VARCHAR (60) NULL,
	ssdq VARCHAR (200) NULL,
	CONSTRAINT PK_cw_dwzd PRIMARY KEY (ztdm, dwbh)
);

CREATE TABLE cw_fylb (
	ztdm VARCHAR (20) NOT NULL,
	fylbbh VARCHAR (30) NOT NULL,
	fylbmc VARCHAR (60) NULL,
	zckmbh VARCHAR (20) NULL,
	zjbmbh VARCHAR (20) NULL,
	zjxmbh VARCHAR (20) NULL,
	CONSTRAINT PK_cw_fylb PRIMARY KEY (ztdm, fylbbh)
);

CREATE TABLE cw_jjflkmzd (
	ztdm VARCHAR (20) NOT NULL,
	jjflkmbh VARCHAR (30) NOT NULL,
	jjflkmmc VARCHAR (255) NULL,
	zccclass VARCHAR (30) NULL,
	CONSTRAINT PK_cw_jjflkmzd PRIMARY KEY (ztdm, jjflkmbh)
);

CREATE TABLE cw_pzfl (
	ztdm VARCHAR (20) NOT NULL,
	kjnd VARCHAR (50) NOT NULL,
	kjqj VARCHAR (50) NOT NULL,
	lxbh VARCHAR (20) NOT NULL,
	pzbh VARCHAR (20) NOT NULL,
	flbh INT NOT NULL,
	pzrq VARCHAR (50) NULL,
	zdr VARCHAR (30) NULL,
	zy VARCHAR (255) NULL,
	kmbh VARCHAR (20) NULL,
	bmbh VARCHAR (30) NULL,
	xmbh VARCHAR (30) NULL,
	xmnm VARCHAR (40) NULL,
	jje DECIMAL (18, 2) DEFAULT (0) NULL,
	dje DECIMAL (18, 2) DEFAULT (0) NULL,
	zclb VARCHAR (20) NULL,
	ywdh VARCHAR (20) NULL,
	dj DECIMAL (18, 2) DEFAULT (0) NULL,
	sl DECIMAL (18, 2) DEFAULT (0) NULL,
	gdzcdm VARCHAR (60) NULL,
	CONSTRAINT PK_cw_pzfl PRIMARY KEY (ztdm, kjnd, kjqj, lxbh, pzbh, flbh)
);

CREATE TABLE cw_rydm (
	ztdm VARCHAR (20) NOT NULL,
	rydm VARCHAR (30) NOT NULL,
	xm VARCHAR (100) NULL,
	bmbh VARCHAR (20) NULL,
	bmmc VARCHAR (255) NULL,
	rylbdm VARCHAR (30) NULL,
	rylb VARCHAR (60) NULL,
	CONSTRAINT PK_cw_rydm PRIMARY KEY (ztdm, rydm)
);

CREATE TABLE cw_xmzd (
	ztdm VARCHAR (20) NOT NULL,
	xmnm VARCHAR (40) NOT NULL,
	bmbh VARCHAR (20) NULL,
	bmmc VARCHAR (255) NULL,
	xmbh VARCHAR (30) NULL,
	xmmc VARCHAR (255) NULL,
	fzrbh VARCHAR (30) NULL,
	fzr VARCHAR (30) NULL,
	bzfl VARCHAR (30) NULL,
	isgk	CHAR (1) DEFAULT ('0') NULL,
	yslx VARCHAR (30) NULL,
	lkx VARCHAR (30) NULL,
	gkglh VARCHAR (30) NULL,
	isdl	CHAR (1) DEFAULT ('0') NULL,
	zjbmbh VARCHAR (20) NULL,
	zjxmbh VARCHAR (20) NULL,
	czrq VARCHAR (20) DEFAULT ('1970-01-01 00:00:00') NULL,
	flsx1 VARCHAR (20) NULL,
	flsx2 VARCHAR (20) NULL,
	flsx3 VARCHAR (20) NULL,
	lbbh VARCHAR (4) NULL,
	lbmc VARCHAR (30) NULL,
	xmlxbh VARCHAR (12) NULL,
	xmlxmc VARCHAR (60) NULL,
	fylb VARCHAR (20) NULL,
	CONSTRAINT PK_cw_xmzd PRIMARY KEY (ztdm, xmnm)
);

CREATE TABLE cw_zcdzd (
	ztdm VARCHAR (20) NOT NULL,
	kjnd VARCHAR (50) NOT NULL,
	kjqj VARCHAR (50) NOT NULL,
	lxbh VARCHAR (20) NOT NULL,
	pzbh VARCHAR (20) NOT NULL,
	flbh INT NOT NULL,
	pzrq VARCHAR (50) NULL,
	zdr VARCHAR (30) NULL,
	zy VARCHAR (255) NULL,
	kmbh VARCHAR (20) NULL,
	bmbh VARCHAR (30) NULL,
	xmbh VARCHAR (30) NULL,
	xmnm VARCHAR (40) NULL,
	jje DECIMAL (18, 2) DEFAULT (0) NULL,
	dje DECIMAL (18, 2) DEFAULT (0) NULL,
	zclb VARCHAR (20) NULL,
	ywdh VARCHAR (20) NULL,
	dj DECIMAL (18, 2) DEFAULT (0) NULL,
	sl DECIMAL (18, 2) DEFAULT (0) NULL,
	gdzcdm VARCHAR (60) NULL,
	CONSTRAINT PK_cw_zcdzd PRIMARY KEY (ztdm, kjnd, kjqj, lxbh, pzbh, flbh)
);

CREATE TABLE cw_zckmdzb (
	ztdm VARCHAR (20) NOT NULL,
	zcflbh VARCHAR (30) NOT NULL,
	zcflmc VARCHAR (60) NULL,
	kmbh VARCHAR (20) NULL,
	startflag VARCHAR (2) DEFAULT ('1') NULL,
	CONSTRAINT PK_cw_zckmdzb PRIMARY KEY (ztdm, zcflbh)
);

CREATE TABLE cw_zwzfdz (
	ztdm VARCHAR (20) NOT NULL,
	kjnd VARCHAR (50) NOT NULL,
	kjqj VARCHAR (50) NOT NULL,
	lxbh VARCHAR (20) NOT NULL,
	pzbh VARCHAR (20) NOT NULL,
	flbh INT NOT NULL,
	pzrq VARCHAR (50) NULL,
	zdr VARCHAR (30) NULL,
	zy VARCHAR (255) NULL,
	kmbh VARCHAR (20) NULL,
	jjflkmbh VARCHAR (20) NULL,
	bmbh VARCHAR (30) NULL,
	xmbh VARCHAR (30) NULL,
	xmnm VARCHAR (40) NULL,
	dch VARCHAR (30) NULL,
	zrrbh VARCHAR (30) NULL,
	zrrmc VARCHAR (60) NULL,
	dwbh VARCHAR (30) NULL,
	dfdw VARCHAR (255) NULL,
	jje DECIMAL (18, 2) DEFAULT (0) NULL,
	dje DECIMAL (18, 2) DEFAULT (0) NULL,
	CONSTRAINT PK_cw_zwzfdz PRIMARY KEY (ztdm, kjnd, kjqj, lxbh, pzbh, flbh)
);

CREATE TABLE zc_bmbd (
	ywdh VARCHAR (20) NOT NULL,
	bh INT NOT NULL,
	zclbdm VARCHAR (20) NULL,
	zclbdm1 VARCHAR (20) NULL,
	bmbh_bdq VARCHAR (20) NULL,
	xmbh_bdq VARCHAR (20) NULL,
	bmbh_bdh VARCHAR (20) NULL,
	xmbh_bdh VARCHAR (20) NULL,
	je DECIMAL (18, 2) DEFAULT (0) NULL,
	ljzj DECIMAL (18, 2) DEFAULT (0) NULL,
	cf1 VARCHAR (60) DEFAULT (TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:mi:ss.ff3')) NULL,
	cf2 VARCHAR (60) NULL,
	cf3 VARCHAR (60) NULL,
	cf4 VARCHAR (60) NULL,
	cf5 VARCHAR (60) NULL,
	cf6 VARCHAR (60) NULL,
	cf7 VARCHAR (60) NULL,
	cf8 VARCHAR (60) NULL,
	cf9 VARCHAR (60) NULL,
	cf10 VARCHAR (60) NULL,
	df1 DECIMAL (18, 2) DEFAULT (0) NULL,
	df2 DECIMAL (18, 2) DEFAULT (0) NULL,
	df3 DECIMAL (18, 2) DEFAULT (0) NULL,
	df4 DECIMAL (18, 2) DEFAULT (0) NULL,
	df5 DECIMAL (18, 2) DEFAULT (0) NULL,
	CONSTRAINT PK_zc_bmbd PRIMARY KEY (ywdh, bh)
);

CREATE TABLE zc_gwkjyxx (
	YWDH VARCHAR (20) NOT NULL,
	jyrq VARCHAR (8) NOT NULL,
	jysj VARCHAR (12) NOT NULL,
	jdbz VARCHAR (1) DEFAULT ('') NOT NULL,
	je DECIMAL (18, 2) DEFAULT (0) NULL,
	wbje DECIMAL (18, 2) DEFAULT (0) NULL,
	bzdm VARCHAR (30) NULL,
	ckrxm VARCHAR (60) NULL,
	yhkh VARCHAR (20) NOT NULL,
	shmc VARCHAR (255) NULL,
	yhbz VARCHAR (120) NULL,
	bz VARCHAR (255) NULL,
	gkyslxdm VARCHAR (4) NULL,
	gklkxdm VARCHAR (20) NULL,
	gkjjfldm VARCHAR (20) NULL,
	gkzclxdm VARCHAR (30) NULL,
	gkfzdm VARCHAR (30) NULL,
	gkyssxdm VARCHAR (4) NULL,
	cf1 VARCHAR (30) NULL,
	cf2 VARCHAR (30) NULL,
	cf3 VARCHAR (30) NULL,
	cf4 VARCHAR (30) NULL,
	cf5 VARCHAR (30) NULL,
	cf6 VARCHAR (30) NULL,
	sjrq VARCHAR (8) NULL,
	fhh VARCHAR (20) NULL,
	jzrq VARCHAR (8) NULL,
	jylx VARCHAR (60) NULL,
	shh VARCHAR (20) NULL,
	zdh VARCHAR (20) NULL,
	lsh VARCHAR (100) NOT NULL,
	jyhb VARCHAR (20) NULL,
	jym VARCHAR (20) NULL,
	sqh VARCHAR (20) NULL,
	dljg VARCHAR (20) NULL,
	zfjg VARCHAR (20) NULL,
	ckh VARCHAR (30) NULL,
	qsrq VARCHAR (8) NULL,
	xfje DECIMAL (18, 2) NULL,
	CONSTRAINT PK_zc_zc_gwkjyxx PRIMARY KEY (jyrq, jysj, yhkh, lsh)
);

CREATE TABLE zc_htxx (
	ywdh VARCHAR (20) NOT NULL,
	htbh VARCHAR (60) NOT NULL,
	htmc VARCHAR (255) NULL,
	dwmc VARCHAR (255) NULL,
	qsrq VARCHAR (8) NULL,
	jsrq VARCHAR (8) NULL,
	htje DECIMAL (18, 2) DEFAULT (0) NULL,
	je1 DECIMAL (18, 2) DEFAULT (0) NULL,
	je2 DECIMAL (18, 2) DEFAULT (0) NULL,
	je3 DECIMAL (18, 2) DEFAULT (0) NULL,
	je4 DECIMAL (18, 2) DEFAULT (0) NULL,
	je5 DECIMAL (18, 2) DEFAULT (0) NULL,
	bz VARCHAR (255) NULL,
	cf1 VARCHAR (60) DEFAULT (TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:mi:ss.ff3')) NULL,
	cf2 VARCHAR (60) NULL,
	cf3 VARCHAR (60) NULL,
	cf4 VARCHAR (60) NULL,
	cf5 VARCHAR (60) NULL,
	cf6 VARCHAR (60) NULL,
	cf7 VARCHAR (60) NULL,
	cf8 VARCHAR (60) NULL,
	cf9 VARCHAR (60) NULL,
	cf10 VARCHAR (60) NULL,
	df1 DECIMAL (18, 2) DEFAULT (0) NULL,
	df2 DECIMAL (18, 2) DEFAULT (0) NULL,
	df3 DECIMAL (18, 2) DEFAULT (0) NULL,
	df4 DECIMAL (18, 2) DEFAULT (0) NULL,
	df5 DECIMAL (18, 2) DEFAULT (0) NULL,
	CONSTRAINT PK_zc_htxx PRIMARY KEY (ywdh, htbh)
);

CREATE TABLE zc_htxx_fj (
	ywdh VARCHAR (20) NOT NULL,
	htbh VARCHAR (60) NOT NULL,
	fileidlist VARCHAR (4000) NULL,
	CONSTRAINT PK_zc_htxx_fj PRIMARY KEY (ywdh, htbh)
);

CREATE TABLE zc_jzcl (
	ywdh VARCHAR (20) NOT NULL,
	bh INT NOT NULL,
	zclbdm VARCHAR (20) NULL,
	zclbdm1 VARCHAR (20) NULL,
	bmbh VARCHAR (20) NULL,
	xmbh VARCHAR (20) NULL,
	zcyz DECIMAL (18, 2) DEFAULT (0) NULL,
	ljzj DECIMAL (18, 2) DEFAULT (0) NULL,
	zcjz DECIMAL (18, 2) DEFAULT (0) NULL,
	srje DECIMAL (18, 2) DEFAULT (0) NULL,
	cf1 VARCHAR (60) DEFAULT (TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:mi:ss.ff3')) NULL,
	cf2 VARCHAR (60) NULL,
	cf3 VARCHAR (60) NULL,
	cf4 VARCHAR (60) NULL,
	cf5 VARCHAR (60) NULL,
	cf6 VARCHAR (60) NULL,
	cf7 VARCHAR (60) NULL,
	cf8 VARCHAR (60) NULL,
	cf9 VARCHAR (60) NULL,
	cf10 VARCHAR (60) NULL,
	df1 DECIMAL (18, 2) DEFAULT (0) NULL,
	df2 DECIMAL (18, 2) DEFAULT (0) NULL,
	df3 DECIMAL (18, 2) DEFAULT (0) NULL,
	df4 DECIMAL (18, 2) DEFAULT (0) NULL,
	df5 DECIMAL (18, 2) DEFAULT (0) NULL,
	CONSTRAINT PK_zc_jzcl PRIMARY KEY (ywdh, bh)
);

CREATE TABLE zc_tkxx (
	ywdh VARCHAR (20) NOT NULL,
	bh INT NOT NULL,
	rzywdh VARCHAR (20) NULL,
	cf1 VARCHAR (60) DEFAULT (TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:mi:ss.ff3')) NULL,
	cf2 VARCHAR (60) NULL,
	cf3 VARCHAR (60) NULL,
	cf4 VARCHAR (60) NULL,
	cf5 VARCHAR (60) NULL,
	cf6 VARCHAR (60) NULL,
	cf7 VARCHAR (60) NULL,
	cf8 VARCHAR (60) NULL,
	cf9 VARCHAR (60) NULL,
	cf10 VARCHAR (60) NULL,
	df1 DECIMAL (18, 2) DEFAULT (0) NULL,
	df2 DECIMAL (18, 2) DEFAULT (0) NULL,
	df3 DECIMAL (18, 2) DEFAULT (0) NULL,
	df4 DECIMAL (18, 2) DEFAULT (0) NULL,
	df5 DECIMAL (18, 2) DEFAULT (0) NULL,
	CONSTRAINT PK_zc_tkxx PRIMARY KEY (ywdh, bh)
);

CREATE TABLE zc_xx (
	ywdh VARCHAR (20) NOT NULL,
	bh INT NOT NULL,
	zclbdm VARCHAR (20) NULL,
	zclbdm1 VARCHAR (20) NULL,
	gdzcdm VARCHAR (20) NULL,
	gdzcmc VARCHAR (100) NULL,
	dj DECIMAL (18, 2) DEFAULT (0) NULL,
	sl DECIMAL (18, 2) DEFAULT (0) NULL,
	je DECIMAL (18, 2) DEFAULT (0) NULL,
	rzrq VARCHAR (50) NULL,
	jsr VARCHAR (20) NULL,
	bmmc VARCHAR (100) NULL,
	bmbh VARCHAR (20) NULL,
	xmbh VARCHAR (20) NULL,
	iszcjz VARCHAR (50) NULL,
	iszt VARCHAR (50) NULL,
	synx INT	DEFAULT (0) NULL,
	zjff VARCHAR (50) NULL,
	zjfs VARCHAR (20) NULL,
	isdl VARCHAR (50) DEFAULT ('0') NULL,
	cf4 VARCHAR (60) NULL,
	cf5 VARCHAR (60) NULL,
	cf6 VARCHAR (60) DEFAULT (TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:mi:ss.ff3')) NULL,
	cf7 VARCHAR (60) NULL,
	cf8 VARCHAR (60) NULL,
	cf9 VARCHAR (60) NULL,
	cf10 VARCHAR (60) NULL,
	df1 DECIMAL (18, 2) DEFAULT (0) NULL,
	df2 DECIMAL (18, 2) DEFAULT (0) NULL,
	df3 DECIMAL (18, 2) DEFAULT (0) NULL,
	df4 DECIMAL (18, 2) DEFAULT (0) NULL,
	df5 DECIMAL (18, 2) DEFAULT (0) NULL,
	CONSTRAINT PK_zc_xx PRIMARY KEY (ywdh, bh)
);

CREATE TABLE zc_ywlx (
	ywdh VARCHAR (20) NOT NULL,
	ywlx VARCHAR (50) NULL,
	ywms VARCHAR (255) NULL,
	jsr VARCHAR (20) NULL,
	bmmc VARCHAR (100) NULL,
	issh VARCHAR (50) NULL,
	cwclrq VARCHAR (50) NULL,
	cwzdzt VARCHAR (50) NULL,
	cwshr VARCHAR (20) NULL,
	cwsm VARCHAR (255) NULL,
	pzrq VARCHAR (8) NULL,
	pzlxbh VARCHAR (20) NULL,
	pzbh VARCHAR (20) NULL,
	ztdm VARCHAR (20) NULL,
	cf1 VARCHAR (60) NULL,
	cf2 VARCHAR (60) NULL,
	cf3 VARCHAR (60) DEFAULT (TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:mi:ss.ff3')) NULL,
	cf4 VARCHAR (60) NULL,
	cf5 VARCHAR (60) NULL,
	cf6 VARCHAR (60) NULL,
	cf7 VARCHAR (60) NULL,
	cf8 VARCHAR (60) NULL,
	cf9 VARCHAR (60) NULL,
	cf10 VARCHAR (60) NULL,
	df1 DECIMAL (18, 2) DEFAULT (0) NULL,
	df2 DECIMAL (18, 2) DEFAULT (0) NULL,
	df3 DECIMAL (18, 2) DEFAULT (0) NULL,
	df4 DECIMAL (18, 2) DEFAULT (0) NULL,
	df5 DECIMAL (18, 2) DEFAULT (0) NULL,
	CONSTRAINT PK_zc_ywlx PRIMARY KEY (ywdh)
);

CREATE TABLE zc_zcjf (
	ywdh VARCHAR (20) DEFAULT ('') NOT NULL,
	bmbh VARCHAR (20) DEFAULT ('') NOT NULL,
	xmbh VARCHAR (20) DEFAULT ('') NOT NULL,
	je DECIMAL (18, 2) DEFAULT (0) NULL,
	fylb VARCHAR (20) NULL,
	cf1 VARCHAR (60) NULL,
	cf2 VARCHAR (60) DEFAULT (TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:mi:ss.ff3')) NULL,
	cf3 VARCHAR (60) NULL,
	cf4 VARCHAR (60) NULL,
	cf5 VARCHAR (60) NULL,
	cf6 VARCHAR (60) NULL,
	cf7 VARCHAR (60) NULL,
	cf8 VARCHAR (60) NULL,
	cf9 VARCHAR (60) NULL,
	cf10 VARCHAR (60) NULL,
	df1 DECIMAL (18, 2) DEFAULT (0) NULL,
	df2 DECIMAL (18, 2) DEFAULT (0) NULL,
	df3 DECIMAL (18, 2) DEFAULT (0) NULL,
	df4 DECIMAL (18, 2) DEFAULT (0) NULL,
	df5 DECIMAL (18, 2) DEFAULT (0) NULL,
	CONSTRAINT PK_zc_zcjf PRIMARY KEY (ywdh, bmbh, xmbh)
);

CREATE TABLE zc_zczj (
	ywdh VARCHAR (20) NOT NULL,
	bh INT NOT NULL,
	zclbdm VARCHAR (20) NULL,
	zclbdm1 VARCHAR (20) NULL,
	fylb VARCHAR (20) NULL,
	bmbh VARCHAR (20) NULL,
	xmbh VARCHAR (20) NULL,
	je DECIMAL (18, 2) DEFAULT (0) NULL,
	cf1 VARCHAR (60) DEFAULT (TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:mi:ss.ff3')) NULL,
	cf2 VARCHAR (60) NULL,
	cf3 VARCHAR (60) NULL,
	cf4 VARCHAR (60) NULL,
	cf5 VARCHAR (60) NULL,
	cf6 VARCHAR (60) NULL,
	cf7 VARCHAR (60) NULL,
	cf8 VARCHAR (60) NULL,
	cf9 VARCHAR (60) NULL,
	cf10 VARCHAR (60) NULL,
	df1 DECIMAL (18, 2) DEFAULT (0) NULL,
	df2 DECIMAL (18, 2) DEFAULT (0) NULL,
	df3 DECIMAL (18, 2) DEFAULT (0) NULL,
	df4 DECIMAL (18, 2) DEFAULT (0) NULL,
	df5 DECIMAL (18, 2) DEFAULT (0) NULL,
	CONSTRAINT PK_zc_zczj PRIMARY KEY (ywdh, bh)
);

CREATE TABLE zc_zczj_lb (
	ywdh VARCHAR (20) DEFAULT ('') NOT NULL,
	bh INT	DEFAULT (0) NOT NULL,
	zclbdm VARCHAR (20) NULL,
	zclbdm1 VARCHAR (20) NULL,
	bmbh VARCHAR (20) NULL,
	xmbh VARCHAR (20) NULL,
	je DECIMAL (18, 2) DEFAULT (0) NULL,
	cf1 VARCHAR (60) DEFAULT (TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:mi:ss.ff3')) NULL,
	cf2 VARCHAR (60) NULL,
	cf3 VARCHAR (60) NULL,
	cf4 VARCHAR (60) NULL,
	cf5 VARCHAR (60) NULL,
	cf6 VARCHAR (60) NULL,
	cf7 VARCHAR (60) NULL,
	cf8 VARCHAR (60) NULL,
	cf9 VARCHAR (60) NULL,
	cf10 VARCHAR (60) NULL,
	df1 DECIMAL (18, 2) DEFAULT (0) NULL,
	df2 DECIMAL (18, 2) DEFAULT (0) NULL,
	df3 DECIMAL (18, 2) DEFAULT (0) NULL,
	df4 DECIMAL (18, 2) DEFAULT (0) NULL,
	df5 DECIMAL (18, 2) DEFAULT (0) NULL,
	CONSTRAINT PK_zc_zczj_lb PRIMARY KEY (ywdh, bh)
);

CREATE TABLE zc_zczj_yt (
	ywdh VARCHAR (20) NOT NULL,
	bh INT NOT NULL,
	fylb VARCHAR (20) NULL,
	bmbh VARCHAR (20) NULL,
	xmbh VARCHAR (20) NULL,
	je DECIMAL (18, 2) DEFAULT (0) NULL,
	cf1 VARCHAR (60) DEFAULT (TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:mi:ss.ff3')) NULL,
	cf2 VARCHAR (60) NULL,
	cf3 VARCHAR (60) NULL,
	cf4 VARCHAR (60) NULL,
	cf5 VARCHAR (60) NULL,
	cf6 VARCHAR (60) NULL,
	cf7 VARCHAR (60) NULL,
	cf8 VARCHAR (60) NULL,
	cf9 VARCHAR (60) NULL,
	cf10 VARCHAR (60) NULL,
	df1 DECIMAL (18, 2) DEFAULT (0) NULL,
	df2 DECIMAL (18, 2) DEFAULT (0) NULL,
	df3 DECIMAL (18, 2) DEFAULT (0) NULL,
	df4 DECIMAL (18, 2) DEFAULT (0) NULL,
	df5 DECIMAL (18, 2) DEFAULT (0) NULL,
	CONSTRAINT PK_zc_zczj_yt PRIMARY KEY (ywdh, bh)
);

CREATE TABLE zc_zfxx (
	ywdh VARCHAR (20) NOT NULL,
	bh INT NOT NULL,
	grfs VARCHAR (50) NULL,
	dfdw VARCHAR (255) NULL,
	yhzh VARCHAR (30) NULL,
	khh VARCHAR (255) NULL,
	dfcity VARCHAR (30) NULL,
	dch VARCHAR (30) NULL,
	je DECIMAL (18, 2) DEFAULT (0) NULL,
	cf1 VARCHAR (60) NULL,
	cf2 VARCHAR (60) NULL,
	cf3 VARCHAR (60) NULL,
	cf4 VARCHAR (60) NULL,
	cf5 VARCHAR (60) DEFAULT (TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:mi:ss.ff3')) NULL,
	cf6 VARCHAR (60) NULL,
	cf7 VARCHAR (60) NULL,
	cf8 VARCHAR (60) NULL,
	cf9 VARCHAR (60) NULL,
	cf10 VARCHAR (60) NULL,
	df1 DECIMAL (18, 2) DEFAULT (0) NULL,
	df2 DECIMAL (18, 2) DEFAULT (0) NULL,
	df3 DECIMAL (18, 2) DEFAULT (0) NULL,
	df4 DECIMAL (18, 2) DEFAULT (0) NULL,
	df5 DECIMAL (18, 2) DEFAULT (0) NULL,
	CONSTRAINT PK_zc_zfxx PRIMARY KEY (ywdh, bh)
);

CREATE TABLE zc_dzfp (
	dzfph VARCHAR (60) NOT NULL,
	fpdm VARCHAR (30) NULL,
	fphm VARCHAR (30) NULL,
	hyfl VARCHAR (60) NULL,
	swlx VARCHAR (20) NULL,
	kprq VARCHAR (8) DEFAULT ('19700101') NULL,
	fkfsbh VARCHAR (30) NULL,
	fkdwmc VARCHAR (100) NULL,
	fkdzdh VARCHAR (100) NULL,
	fkkhh VARCHAR (100) NULL,
	kpfsbh VARCHAR (30) NULL,
	kpdwmc VARCHAR (100) NULL,
	kpdzdh VARCHAR (100) NULL,
	kpkhh VARCHAR (100) NULL,
	jbr VARCHAR (30) NULL,
	bz VARCHAR (100) NULL,
	ywdh VARCHAR (20) NULL,
	pznm VARCHAR (20) NULL,
	zdr VARCHAR (30) NULL,
	lrr VARCHAR (30) NULL,
	lrrq VARCHAR (8) DEFAULT ('19700101') NULL,
	lybh VARCHAR (30) NULL,
	kjnd VARCHAR (4) DEFAULT ('1970') NULL,
	kjqj VARCHAR (2) DEFAULT ('01') NULL,
	pjlx VARCHAR (30) NULL,
	bmbh VARCHAR (20) NULL,
	xmbh VARCHAR (20) NULL,
	isbx VARCHAR (1) NULL,
	fpnr VARCHAR (255) NULL,
	je DECIMAL (18, 2) DEFAULT (0) NULL,
	se DECIMAL (18, 2) DEFAULT (0) NULL,
	zje DECIMAL (18, 2) DEFAULT (0) NULL,
	yzm VARCHAR (30) NULL,
	ischeck VARCHAR (1) NULL,
	ssdq VARCHAR (60) NULL,
	url VARCHAR (255) NULL,
	CONSTRAINT PK_zc_dzfp PRIMARY KEY (dzfph)
);

CREATE TABLE zc_dzfpmx (
	dzfph VARCHAR (60) NOT NULL,
	bh INT NOT NULL,
	xmmc VARCHAR (100) NULL,
	dw VARCHAR (30) NULL,
	shul INT	DEFAULT (0) NULL,
	dj DECIMAL (18, 2) DEFAULT (0) NULL,
	je DECIMAL (18, 2) DEFAULT (0) NULL,
	sl DECIMAL (18, 2) DEFAULT (0) NULL,
	se DECIMAL (18, 2) DEFAULT (0) NULL,
	zje DECIMAL (18, 2) DEFAULT (0) NULL,
	CONSTRAINT PK_zc_dzfpmx PRIMARY KEY (dzfph, bh)
);

CREATE TABLE zc_xmdjmx (
	pllsh VARCHAR (120) NOT NULL,
	ywdh VARCHAR (20) NOT NULL,
	rq VARCHAR (8) NULL,
	bmbh VARCHAR (20) NULL,
	xmbh VARCHAR (30) NULL,
	zy VARCHAR (255) NULL,
	jdje DECIMAL (18, 2) NULL,
	llr VARCHAR (30) NULL,
	issh VARCHAR (1) NULL,
	shrq VARCHAR (8) NULL,
	shr VARCHAR (30) NULL,
	sbr VARCHAR (30) NULL,
	sbrq VARCHAR (8) NULL,
	cf1 VARCHAR (255) NULL,
	cf2 VARCHAR (255) NULL,
	cf3 VARCHAR (255) NULL,
	cf4 VARCHAR (255) NULL,
	cf5 VARCHAR (255) NULL,
	cf6 VARCHAR (255) NULL,
	cf7 VARCHAR (255) NULL,
	cf8 VARCHAR (255) NULL,
	cf9 VARCHAR (255) NULL,
	cf10 VARCHAR (255) NULL,
	df1 DECIMAL (18, 2) NULL,
	df2 DECIMAL (18, 2) NULL,
	df3 DECIMAL (18, 2) NULL,
	df4 DECIMAL (18, 2) NULL,
	df5 DECIMAL (18, 2) NULL,
	CONSTRAINT PK_zc_xmdjmx PRIMARY KEY (pllsh, ywdh)
);

CREATE TABLE zc_xmeddjmx (
	pllsh VARCHAR (120) NOT NULL,
	ywdh VARCHAR (20) NOT NULL,
	rq VARCHAR (8) NULL,
	bmbh VARCHAR (20) NULL,
	xmbh VARCHAR (30) NULL,
	edkzbm VARCHAR (20) NULL,
	zy VARCHAR (255) NULL,
	jdje DECIMAL (18, 2) NULL,
	llr VARCHAR (30) NULL,
	issh VARCHAR (1) NULL,
	shrq VARCHAR (8) NULL,
	shr VARCHAR (30) NULL,
	sbr VARCHAR (30) NULL,
	sbrq VARCHAR (8) NULL,
	cf1 VARCHAR (255) NULL,
	cf2 VARCHAR (255) NULL,
	cf3 VARCHAR (255) NULL,
	cf4 VARCHAR (255) NULL,
	cf5 VARCHAR (255) NULL,
	cf6 VARCHAR (255) NULL,
	cf7 VARCHAR (255) NULL,
	cf8 VARCHAR (255) NULL,
	cf9 VARCHAR (255) NULL,
	cf10 VARCHAR (255) NULL,
	df1 DECIMAL (18, 2) NULL,
	df2 DECIMAL (18, 2) NULL,
	df3 DECIMAL (18, 2) NULL,
	df4 DECIMAL (18, 2) NULL,
	df5 DECIMAL (18, 2) NULL,
	CONSTRAINT PK_zc_xmeddjmx PRIMARY KEY (pllsh, ywdh)
);

CREATE TABLE mapping_department (
	dept_code VARCHAR (50) NOT NULL,
	dept_name VARCHAR (50) NULL,
	ztdm VARCHAR (50) NULL,
	bmbh VARCHAR (50) NULL,
	CONSTRAINT PK_mapping_department PRIMARY KEY (dept_code)
);


alter table ZC_YWLX add billid varchar(60 char)  NULL;
alter table ZC_YWLX add billdefine varchar(60 char)  NULL;
alter table ZC_YWLX add MODIFYTIME varchar(60 char)  NULL;
alter table ZC_YWLX add INPUTTIME varchar(60 char)  NULL;

alter table ZC_XX add ZCLBMXDM varchar(60 char)  NULL;
alter table ZC_XX add ZCLBMXDM1 varchar(60 char)  NULL;
alter table ZC_XX add INPUTTIME varchar(60 char)  NULL;

alter table ZC_BMBD add INPUTTIME varchar(60 char)  NULL;

alter table ZC_JZCL add INPUTTIME varchar(60 char)  NULL;

alter table ZC_TKXX add INPUTTIME varchar(60 char)  NULL;

alter table ZC_ZCJF add INPUTTIME varchar(60 char)  NULL;

alter table ZC_ZCJF add MODIFYTIME varchar(60 char)  NULL;

alter table ZC_ZCZJ add INPUTTIME varchar(60 char)  NULL;

alter table ZC_ZCZJ_LB add INPUTTIME varchar(60 char)  NULL;

alter table ZC_ZCZJ_YT add INPUTTIME varchar(60 char)  NULL;

alter table ZC_ZFXX add INPUTTIME varchar(60 char)  NULL;


