--------删除建账单垃圾数据------------
DELETE FROM GAMS_INSPECTIONENTRY_PAYINFO gip WHERE MASTER_ID IN (SELECT ID FROM GAMS_INSPECTIONENTRY gi WHERE gi.ORG_ID <> (SELECT ID FROM ORG o2)); /*无数据无法测试*/

DELETE FROM GAMS_INSPECTIONENTRY_CHUCH gic WHERE MASTER_ID IN (SELECT ID FROM GAMS_INSPECTIONENTRY_LINGYINFO gil WHERE MASTER_ID IN (SELECT ID FROM GAMS_INSPECTIONENTRY_DETAIL gid WHERE MASTER_ID IN (SELECT ID FROM GAMS_INSPECTIONENTRY gi WHERE gi.ORG_ID <> (SELECT ID FROM ORG o2))));

DELETE FROM GAMS_INSPECTIONENTRY_LINGYINFO gil WHERE MASTER_ID IN (SELECT ID FROM GAMS_INSPECTIONENTRY_DETAIL gid WHERE MASTER_ID IN (SELECT ID FROM GAMS_INSPECTIONENTRY gi WHERE gi.ORG_ID <> (SELECT ID FROM ORG o2)));

DELETE FROM GAMS_INSPECTIONENTRY_DETAIL gid WHERE MASTER_ID IN (SELECT ID FROM GAMS_INSPECTIONENTRY gi WHERE gi.ORG_ID <> (SELECT ID FROM ORG o2));

DELETE FROM GAMS_INSPECTIONENTRY gi WHERE gi.ORG_ID <> (SELECT ID FROM ORG o2);

-----------删除部门垃圾数据--------

DELETE FROM GAMS_JC_DEPARTMENT gjd WHERE gjd.ORGID <> (SELECT ID FROM ORG o2);

-----------删除人员垃圾数据---------

DELETE FROM GAMS_JC_PERSONNEL gjp WHERE gjp.ORGID <> (SELECT ID FROM ORG o2);

-----------删除存放地点垃圾数据---------

DELETE FROM  GAMS_JC_DEPOSITARY gjd WHERE gjd.ORGID <> (SELECT ID FROM ORG o2);

-----------删除资产归属垃圾数据---------

DELETE FROM  gams_jc_zicgs a WHERE a.ORGID <> (SELECT ID FROM ORG o2);




-----------删除资产归属垃圾数据---------

DELETE FROM  gams_unitdatatrans_detail a WHERE a.ORGID <> (SELECT ID FROM ORG o2);

DELETE FROM  gams_card_fw a WHERE a.ORGUNIT <> (SELECT ID FROM ORG o2);



