SELECT count(gcc.CARDID),gcc.CARDID FROM GAMS_CARD_CHANGE gcc WHERE gcc.BIZTYPE = 'com.jiuqi.np.gams2.business.bill.HandoverBillDefine' GROUP BY gcc.CARDID ORDER BY count(CARDID) DESC ;
	
6ED57E2980000201142A67CE25F1F9CD

SELECT * FROM GAMS_CARD gc WHERE gc.ID = '6ED57E2980000201142A67CE25F1F9CD';

SELECT max(CAOZSJ),CARDID 
--SELECT gcc.CAOZSJ ,gcc.*
FROM GAMS_CARD_CHANGE gcc WHERE gcc.BIZTYPE = 'com.jiuqi.np.gams2.business.bill.HandoverBillDefine' AND gcc.BIANDCZSXH = 1  

AND gcc.CARDID = '6ED57E2980000201142A67CE25F1F9CD' 
GROUP BY CARDID;

SELECT gcc.SHIYBM FROM GAMS_CARD_CHANGE gcc,(SELECT max(CAOZSJ) CAOZSJ,CARDID 
--SELECT gcc.CAOZSJ ,gcc.*
FROM GAMS_CARD_CHANGE gcc WHERE gcc.BIZTYPE = 'com.jiuqi.np.gams2.business.bill.HandoverBillDefine' AND gcc.BIANDCZSXH = 1  

AND gcc.CARDID = '6ED57E2980000201142A67CE25F1F9CD' 
GROUP BY CARDID)  a WHERE  a.CAOZSJ = gcc.CAOZSJ AND a.CARDID  = gcc.cardid AND gcc.BIANDCZSXH = 1 ;

UPDATE GAMS_CARD c SET c.SHIYBM = (SELECT gcc.SHIYBM FROM GAMS_CARD_CHANGE gcc,(SELECT max(CAOZSJ) CAOZSJ,CARDID 
--SELECT gcc.CAOZSJ ,gcc.*
FROM GAMS_CARD_CHANGE gcc WHERE gcc.BIZTYPE = 'com.jiuqi.np.gams2.business.bill.HandoverBillDefine' AND gcc.BIANDCZSXH = 1  

AND gcc.CARDID = '6ED57E2980000201142A67CE25F1F9CD' 
GROUP BY CARDID)  a WHERE  a.CAOZSJ = gcc.CAOZSJ AND a.CARDID  = gcc.cardid AND gcc.BIANDCZSXH = 1 ) WHERE c.id = gcc.cardid;

UPDATE 

UPDATE
	GAMS_CARD c
SET
	c.SHIYBM = (
	SELECT
		SHIYBM
	FROM
		GAMS_CARD_USEINFO gcu
	WHERE
		gcu.BIZTYPE = 'com.jiuqi.np.gams2.business.bill.HandoverBillDefine'
		AND c.SHIYBM <> gcu.SHIYBM
		AND c.OBJECTID = gcu.CARDOBJECTID
	GROUP BY
		SHIYBM)
		
		
		
		
		
SELECT SHIYBM ,SHIYBM_D,biandczsxh FROM GAMS_CARD_CHANGE gcc LEFT JOIN GAMS_JC_DEPARTMENT gjd ON gcc.SHIYBM = gjd.id WHERE gcc.BIZID = (SELECT ID FROM GAMS_HANDOVER gw WHERE gw.BILL_CODE = 'ZCJJ2019000006') ;

SELECT * FROM GAMS_HANDOVER_DETAIL  gw WHERE gw.BILL_CODE = 'ZCJJ2020000070';

UPDATE GAMS_CARD SET SHIYBM = '';

SELECT * FROM gams_card_trace;

SELECT * FROM GAMS_CARD gc WHERE gc.ID = '6ED57DCB2000030175EA229ED0DF08D3';

SELECT * FROM GAMS_JC_DEPARTMENT gjd WHERE gjd.id = '6E35DEF160000081BB66D4B506DE7E64';1人工智能与大数据学院办公室

SELECT * FROM GAMS_JC_DEPARTMENT gjd WHERE gjd.id = '6E35DEF180000041350E7B4CC1088D03';2工程与鉴定中心


