SELECT * FROM GAMS_ASSETCHANGE ga ;

SELECT * FROM GAMS_CARD_CHANGE gcc ;

SELECT * FROM GAMS_CARD_TRACE gct ;

SELECT * FROM GAMS_CARD_LOCK gcl ;

SELECT * FROM ORG o ;

select count(c.ID),sum(c.shul),sum(c.jiaz)
  from GAMS_CARD c
  where 1=1
  and c.SHIXRQ > systimestamp 
  and c.ORGUNIT = hextoraw('456E9ADEC0000001FE7C6554025F7E5E')
  and c.ISLASTEST = 1
  and c.CARDSTATE like '0%'
  and c.auditstate='2'

SELECT count(1), SHIXRQ FROM GAMS_CARD GROUP BY SHIXRQ;
  
SELECT count(1), SHIXRQ FROM GAMS_CARD_TYSB gct GROUP BY SHIXRQ;

SELECT count(1), SHIXRQ FROM GAMS_CARD_ZYSB gcz GROUP BY SHIXRQ;

SELECT count(1), SHIXRQ FROM GAMS_CARD_TSDA gct GROUP BY SHIXRQ;

SELECT count(1), SHIXRQ FROM GAMS_CARD_JJYJZJ gcj GROUP BY SHIXRQ;


UPDATE GAMS_CARD_JJYJZJ SET SHIXRQ = to_date('9999-12-01 00:00:00','yyyy-mm-dd HH24:mi:ss') WHERE SHIXRQ IS NULL;

UPDATE GAMS_CARD_TSDA SET SHIXRQ = to_date('9999-12-01 00:00:00','yyyy-mm-dd HH24:mi:ss') WHERE SHIXRQ IS NULL;

UPDATE GAMS_CARD_ZYSB SET SHIXRQ = to_date('9999-12-01 00:00:00','yyyy-mm-dd HH24:mi:ss') WHERE SHIXRQ IS NULL;

UPDATE GAMS_CARD_TYSB SET SHIXRQ = to_date('9999-12-01 00:00:00','yyyy-mm-dd HH24:mi:ss') WHERE SHIXRQ IS NULL;

UPDATE GAMS_CARD SET SHIXRQ = to_date('9999-12-01 00:00:00','yyyy-mm-dd HH24:mi:ss') WHERE SHIXRQ IS NULL;

SELECT gc.ORGUNIT FROM gams_card gc WHERE gc.YUANZCBH = '229';

83F9BC15767B4107B69B781AB0D4E194

SELECT * FROM GAMS_CARDBATCHIMPORT_ANNEX;

SELECT * FROM ORG o ;