SELECT * FROM NP_USER nu ;

SELECT * FROM AUTHZ_IDENTITY ai 

SELECT * FROM AUTHZ_ROLE ar ;


SELECT * FROM GAMS_ASSETDEPREC_H gah ;

SELECT * FROM GAMS_ASSETDEPREC_I gai ;

SELECT * FROM GAMS_ASSETDEPREC_I gai WHERE CARD_ID =(SELECT gc.ID FROM GAMS_CARD gc WHERE gc.BILLCODE = 'TY2020002627');

SELECT * FROM GAMS_CARD gc WHERE gc.ID = (SELECT card_id FROM GAMS_ASSETDEPREC_I gai WHERE gai.ID = '6F7140DC400109818B096312354E3A97');

SELECT * FROM GAMS_ASSETDEPRECDETAIL ga WHERE ga.JIZQJ = '202007' AND ga.CARD_ID = (SELECT gc.ID FROM GAMS_CARD gc WHERE gc.BILLCODE = 'TY2020002627');

--折旧数据，通过数据迁移过来的的历史折旧单，删除后，卡片上还有折旧记录
CREATE TABLE GAMS_ASSETDEPRECDETAIL_bak0916 AS SELECT * FROM GAMS_ASSETDEPRECDETAIL;

DELETE FROM GAMS_ASSETDEPRECDETAIL ga WHERE ga.JIZQJ = '202008'; 

SELECT JIZQJ FROM GAMS_ASSETDEPRECDETAIL ga GROUP BY ga.JIZQJ ;

SELECT a.YITZJYS FROM GAMS_card a WHERE a.BILLCODE = 'TY2020002627';

SELECT gct.YITZJYS FROM GAMS_CARD_TYSB gct WHERE gct.BILLCODE = 'TY2020002627';

UPDATE GAMS_CARD_TYSB a SET a.YITZJYS = (SELECT YITZJYS FROM GAMS_CARD gc WHERE gc.id = a.id );
--38,846
SELECT
	gc.BILLCODE ,
	gc.YITZJYS AS "卡片表折旧",
	gct.YITZJYS as "通用设备折旧表"
FROM
	GAMS_ASSETDEPRECDETAIL_BAK0916 gab
LEFT JOIN GAMS_CARD gc ON
	gab.CARD_ID = gc.ID
LEFT JOIN GAMS_CARD_TYSB gct ON
	gab.CARD_ID = gct.ID
WHERE
	gab.JIZQJ = '202008' 
	AND gc.YITZJYS <> gct.YITZJYS AND gct.YITZJYS IS NOT NULL ;

	
UPDATE
	GAMS_CARD_TYSB a
SET
	a.YITZJYS = (
	SELECT
		gc.YITZJYS
	FROM
		GAMS_ASSETDEPRECDETAIL_BAK0916 gab
	LEFT JOIN GAMS_CARD gc ON
		gc.ID = gab.CARD_ID
	WHERE
		gab.JIZQJ = '202008'
		AND gc.ID = a.ID )
WHERE
	a.yitzjys IS NOT NULL ;


CREATE TABLE GAMS_CARD_TYSB_b AS SELECT * FROM GAMS_CARD_TYSB gct ;
DROP TABLE GAMS_CARD_TYSB 

CREATE TABLE GAMS_CARD_TYSB AS SELECT * FROM GAMS_CARD_TYSB_b gct ;

Updated Rows	11205
Updated Rows	1379
Updated Rows	15
Updated Rows	80
Updated Rows	6477
Updated Rows	0
Updated Rows	0
Updated Rows	0
--备份卡片
CREATE TABLE GAMS_CARD_TYSB_bal1917 AS SELECT * FROM GAMS_CARD_TYSB;
CREATE TABLE GAMS_CARD_ZYSB_bal1917 AS SELECT * FROM GAMS_CARD_ZYSB;
CREATE TABLE GAMS_CARD_CL_bal1917 AS SELECT * FROM GAMS_CARD_CL;
CREATE TABLE GAMS_CARD_FW_bal1917 AS SELECT * FROM GAMS_CARD_FW;
CREATE TABLE GAMS_CARD_JJYJZJ_bal1917 AS SELECT * FROM GAMS_CARD_JJYJZJ;
--更新通用卡片已提折旧月数
UPDATE
	GAMS_CARD_TYSB a
SET
	a.YITZJYS = a.YITZJYS -1
WHERE
	a.YITZJYS IS NOT NULL
	AND a.id IN (
	SELECT
		gab.CARD_ID
	FROM
		GAMS_ASSETDEPRECDETAIL_BAK0916 gab
	WHERE
		gab.JIZQJ = '202008');
--更新专用卡片已提折旧月数
UPDATE
	GAMS_CARD_ZYSB a
SET
	a.YITZJYS = a.YITZJYS -1
WHERE
	a.YITZJYS IS NOT NULL
	AND a.id IN (
	SELECT
		gab.CARD_ID
	FROM
		GAMS_ASSETDEPRECDETAIL_BAK0916 gab
	WHERE
		gab.JIZQJ = '202008');
--更新GAMS_CARD_CL已提折旧月数
UPDATE
	GAMS_CARD_CL a
SET
	a.YITZJYS = a.YITZJYS -1
WHERE
	a.YITZJYS IS NOT NULL
	AND a.id IN (
	SELECT
		gab.CARD_ID
	FROM
		GAMS_ASSETDEPRECDETAIL_BAK0916 gab
	WHERE
		gab.JIZQJ = '202008');
--更新GAMS_CARD_FW已提折旧月数
UPDATE
	GAMS_CARD_FW a
SET
	a.YITZJYS = a.YITZJYS -1
WHERE
	a.YITZJYS IS NOT NULL
	AND a.id IN (
	SELECT
		gab.CARD_ID
	FROM
		GAMS_ASSETDEPRECDETAIL_BAK0916 gab
	WHERE
		gab.JIZQJ = '202008');
--更新GAMS_CARD_JJYJZJ已提折旧月数
UPDATE
	GAMS_CARD_JJYJZJ a
SET
	a.YITZJYS = a.YITZJYS -1
WHERE
	a.YITZJYS IS NOT NULL
	AND a.id IN (
	SELECT
		gab.CARD_ID
	FROM
		GAMS_ASSETDEPRECDETAIL_BAK0916 gab
	WHERE
		gab.JIZQJ = '202008');

SELECT count(1) FROM GAMS_ASSETDEPRECDETAIL_BAK0916 a WHERE a.JIZQJ = '202008'




	
	
	
	
	